//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentHabitacion.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceTextException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTextException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntelligentHabitacion.Exception.ResourceTextException", typeof(ResourceTextException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address must be entered..
        /// </summary>
        public static string ADDRESS_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City&apos;s name must be entered..
        /// </summary>
        public static string CITY_EMPTY {
            get {
                return ResourceManager.GetString("CITY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code must be entered..
        /// </summary>
        public static string CODE_EMPTY {
            get {
                return ResourceManager.GetString("CODE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is invalid..
        /// </summary>
        public static string CODE_INVALID {
            get {
                return ResourceManager.GetString("CODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a code to reset your password..
        /// </summary>
        public static string CODE_RESET_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("CODE_RESET_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to the administrator has been lost..
        /// </summary>
        public static string CONNECTION_ADMINISTRATOR_LOST {
            get {
                return ResourceManager.GetString("CONNECTION_ADMINISTRATOR_LOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Abbreviation Country must be entered..
        /// </summary>
        public static string COUNTRY_ABBREVIATION_EMPTY {
            get {
                return ResourceManager.GetString("COUNTRY_ABBREVIATION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Country&apos;s name must be entered..
        /// </summary>
        public static string COUNTRY_EMPTY {
            get {
                return ResourceManager.GetString("COUNTRY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password must be entered..
        /// </summary>
        public static string CURRENT_PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("CURRENT_PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is invalid..
        /// </summary>
        public static string CURRENT_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("CURRENT_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address has already been registered..
        /// </summary>
        public static string EMAIL_ALREADYBEENREGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADYBEENREGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail must be entered..
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The E-mail is invalid..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired code. Request a new one..
        /// </summary>
        public static string EXPIRED_CODE {
            get {
                return ResourceManager.GetString("EXPIRED_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend was not found..
        /// </summary>
        public static string FRIEND_NOT_FOUND {
            get {
                return ResourceManager.GetString("FRIEND_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters..
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user..
        /// </summary>
        public static string INVALID_USER {
            get {
                return ResourceManager.GetString("INVALID_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid monthly rent..
        /// </summary>
        public static string MONTHLYRENT_INVALID {
            get {
                return ResourceManager.GetString("MONTHLYRENT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be entered..
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The neighborhood must be entered..
        /// </summary>
        public static string NEIGHBORHOOD_EMPTY {
            get {
                return ResourceManager.GetString("NEIGHBORHOOD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network&apos;s name and the password must be entered..
        /// </summary>
        public static string NETWORKINFORMATIONS_INVALID {
            get {
                return ResourceManager.GetString("NETWORKINFORMATIONS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be entered..
        /// </summary>
        public static string NUMBER_EMPTY {
            get {
                return ResourceManager.GetString("NUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameters are null or empty..
        /// </summary>
        public static string PARAMETERS_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("PARAMETERS_NULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be entered..
        /// </summary>
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not the same as password confirmation..
        /// </summary>
        public static string PASSWORD_NOT_SAME_CONFIRMATION {
            get {
                return ResourceManager.GetString("PASSWORD_NOT_SAME_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One phonenumber must be entered for the Emergency contact {0}..
        /// </summary>
        public static string PHONENUMBER_EMERGENCY_CONTACT_EMPTY {
            get {
                return ResourceManager.GetString("PHONENUMBER_EMERGENCY_CONTACT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Emergency contact&apos;s {0} phonenumber is invalid..
        /// </summary>
        public static string PHONENUMBER_EMERGENCY_CONTACT_INVALID {
            get {
                return ResourceManager.GetString("PHONENUMBER_EMERGENCY_CONTACT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One phone number must be entered..
        /// </summary>
        public static string PHONENUMBER_EMPTY {
            get {
                return ResourceManager.GetString("PHONENUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number is invalid. (XX) X XXXX-XXXX.
        /// </summary>
        public static string PHONENUMBER_INVALID {
            get {
                return ResourceManager.GetString("PHONENUMBER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product name must be entered..
        /// </summary>
        public static string PRODUCT_NAME_EMPTY {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product was not found..
        /// </summary>
        public static string PRODUCT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PRODUCT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The push notification id is invalid..
        /// </summary>
        public static string PUSHNOTIFICATION_INVALID {
            get {
                return ResourceManager.GetString("PUSHNOTIFICATION_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity of products is invalid..
        /// </summary>
        public static string QUANTITY_PRODUCTS_INVALID {
            get {
                return ResourceManager.GetString("QUANTITY_PRODUCTS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship must be entered..
        /// </summary>
        public static string RELATIONSHIPTO_EMPTY {
            get {
                return ResourceManager.GetString("RELATIONSHIPTO_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One code to reset the password is requerid..
        /// </summary>
        public static string REQUERED_CODE_RESET_PASSWORD {
            get {
                return ResourceManager.GetString("REQUERED_CODE_RESET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Emergency contact&apos;s name {0} must be entered..
        /// </summary>
        public static string THE_NAME_EMERGENCY_CONTACT_INVALID {
            get {
                return ResourceManager.GetString("THE_NAME_EMERGENCY_CONTACT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is invalid. (XX) X XXXX-XXXX.
        /// </summary>
        public static string THE_PHONENUMBER_INVALID {
            get {
                return ResourceManager.GetString("THE_PHONENUMBER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Relationship with the Emergency contact {0} must be entered..
        /// </summary>
        public static string THE_RELATIONSHIP_EMERGENCY_CONTACT_INVALID {
            get {
                return ResourceManager.GetString("THE_RELATIONSHIP_EMERGENCY_CONTACT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product&apos;s type is invalid..
        /// </summary>
        public static string TYPE_PRODUCTS_INVALID {
            get {
                return ResourceManager.GetString("TYPE_PRODUCTS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow error.
        /// </summary>
        public static string UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is invalid or don&apos;t unknow.
        /// </summary>
        public static string UNKNOWNDATABASE {
            get {
                return ResourceManager.GetString("UNKNOWNDATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not part of a home. This operation is not allowed at this time..
        /// </summary>
        public static string USER_IS_NOT_PART_OF_A_HOME {
            get {
                return ResourceManager.GetString("USER_IS_NOT_PART_OF_A_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already part of a home. This operation is not allowed at this time..
        /// </summary>
        public static string USER_IS_PART_OF_A_HOME {
            get {
                return ResourceManager.GetString("USER_IS_PART_OF_A_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User and/or password is invalid..
        /// </summary>
        public static string USER_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("USER_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access this resource..
        /// </summary>
        public static string USER_WITHOUT_PERMISSION_ACCESS_RESOURCE {
            get {
                return ResourceManager.GetString("USER_WITHOUT_PERMISSION_ACCESS_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot perform this action..
        /// </summary>
        public static string YOU_CANNNOT_PERMORM_THIS_ACTION {
            get {
                return ResourceManager.GetString("YOU_CANNNOT_PERMORM_THIS_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Zip Code must be entered..
        /// </summary>
        public static string ZIPCODE_EMPTY {
            get {
                return ResourceManager.GetString("ZIPCODE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Zip Code is invalid..
        /// </summary>
        public static string ZIPCODE_INVALID {
            get {
                return ResourceManager.GetString("ZIPCODE_INVALID", resourceCulture);
            }
        }
    }
}
