trigger:
  branches:
    include:
    - master
    - develop

variables:
  NETCORE_VERSION: '3.1.x'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  SolutionPath: 'IntelligentHabitacion.sln'

jobs:
  - job: build_windows
    displayName: Build Windows
    pool:
      vmImage: windows-latest
    steps:
      - task: CmdLine@2
        displayName: 'Clear Local Nuget Cache'
        inputs:
          script: 'nuget locals all-clear'
      - task: MSBuild@1
        displayName: 'Clean Solution'
        inputs:
          solution: $(SolutionPath)
          msbuildArguments: '/t:Clean'
      - task: MSBuild@1
        displayName: Build Solution
        inputs:
          solution: $(SolutionPath)
          configuration: $(buildConfiguration)
          msbuildArguments: '/restore /t:Build /p:ContinuousIntegrationBuild=true /p:Deterministic=false'
      - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
          command: publish
          publishWebProjects: True
          arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
          zipAfterPublish: True
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
          condition: succeeded()