//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentHabitacion.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntelligentHabitacion.App.ResourceText", typeof(ResourceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because live with friends.
        /// </summary>
        internal static string BECAUSE_LIVE_WITH_FRIENDS {
            get {
                return ResourceManager.GetString("BECAUSE_LIVE_WITH_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, ask the new member to go to the App, click on.
        /// </summary>
        internal static string DESCRIPTION_ADDING_FRIEND_FIRST_PART {
            get {
                return ResourceManager.GetString("DESCRIPTION_ADDING_FRIEND_FIRST_PART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and read the Qr Code below :).
        /// </summary>
        internal static string DESCRIPTION_ADDING_FRIEND_SECOND_PART {
            get {
                return ResourceManager.GetString("DESCRIPTION_ADDING_FRIEND_SECOND_PART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow the Cleaning schedule to make the home clean and beautiful..
        /// </summary>
        internal static string DESCRIPTION_CLEAN_HOUSE {
            get {
                return ResourceManager.GetString("DESCRIPTION_CLEAN_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to create a home and be the administrator..
        /// </summary>
        internal static string DESCRIPTION_CREATE_HOME {
            get {
                return ResourceManager.GetString("DESCRIPTION_CREATE_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined on {0}. Today it is exactly {1} that you share a home :).
        /// </summary>
        internal static string DESCRIPTION_DATE_JOINED_THE_HOUSE {
            get {
                return ResourceManager.GetString("DESCRIPTION_DATE_JOINED_THE_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track your household income and expenses..
        /// </summary>
        internal static string DESCRIPTION_FINANCES {
            get {
                return ResourceManager.GetString("DESCRIPTION_FINANCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See useful information about home data..
        /// </summary>
        internal static string DESCRIPTION_HOME_SWEET_HOME {
            get {
                return ResourceManager.GetString("DESCRIPTION_HOME_SWEET_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to be part of a home already created..
        /// </summary>
        internal static string DESCRIPTION_JOIN_HOME {
            get {
                return ResourceManager.GetString("DESCRIPTION_JOIN_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track the foods you have, with amount and expiration date..
        /// </summary>
        internal static string DESCRIPTION_MY_FOOD {
            get {
                return ResourceManager.GetString("DESCRIPTION_MY_FOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See useful information about your friends at home..
        /// </summary>
        internal static string DESCRIPTION_MY_FRIENDS {
            get {
                return ResourceManager.GetString("DESCRIPTION_MY_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to see and/or edit your registry information..
        /// </summary>
        internal static string DESCRIPTION_MY_INFORMATIONS {
            get {
                return ResourceManager.GetString("DESCRIPTION_MY_INFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to the Supermarket? Take a look at the shopping list..
        /// </summary>
        internal static string DESCRIPTION_SHOPPING {
            get {
                return ResourceManager.GetString("DESCRIPTION_SHOPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMMM dd, yyyy.
        /// </summary>
        internal static string FORMAT_DATE {
            get {
                return ResourceManager.GetString("FORMAT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be fun and organized.
        /// </summary>
        internal static string MUST_BE_FUN_AND_ORGANIZED {
            get {
                return ResourceManager.GetString("MUST_BE_FUN_AND_ORGANIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to perform this action?.
        /// </summary>
        internal static string PHRASE_AREYOUSUREEXCUTETHISACTION {
            get {
                return ResourceManager.GetString("PHRASE_AREYOUSUREEXCUTETHISACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh no, you haven&apos;t added any friends yet :(.
        /// </summary>
        internal static string PHRASE_YOU_HAVENT_ADDED_FRIENDS {
            get {
                return ResourceManager.GetString("PHRASE_YOU_HAVENT_ADDED_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rua Mountain Drive.
        /// </summary>
        internal static string PLACEHOLDER_ADDRESS {
            get {
                return ResourceManager.GetString("PLACEHOLDER_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7º Floor.
        /// </summary>
        internal static string PLACEHOLDER_ADDRESSCOMPLEMENT {
            get {
                return ResourceManager.GetString("PLACEHOLDER_ADDRESSCOMPLEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1007.
        /// </summary>
        internal static string PLACEHOLDER_ADDRESSNUMBER {
            get {
                return ResourceManager.GetString("PLACEHOLDER_ADDRESSNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string PLACEHOLDER_AMOUNT {
            get {
                return ResourceManager.GetString("PLACEHOLDER_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gotham City.
        /// </summary>
        internal static string PLACEHOLDER_CITY {
            get {
                return ResourceManager.GetString("PLACEHOLDER_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code received in email.
        /// </summary>
        internal static string PLACEHOLDER_CODE_RECEIVED {
            get {
                return ResourceManager.GetString("PLACEHOLDER_CODE_RECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string PLACEHOLDER_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree of kinship.
        /// </summary>
        internal static string PLACEHOLDER_DEGREE_KINSHIP {
            get {
                return ResourceManager.GetString("PLACEHOLDER_DEGREE_KINSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        internal static string PLACEHOLDER_DUE_DATE {
            get {
                return ResourceManager.GetString("PLACEHOLDER_DUE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bruce@waynetech.com.
        /// </summary>
        internal static string PLACEHOLDER_EMAIL {
            get {
                return ResourceManager.GetString("PLACEHOLDER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother.
        /// </summary>
        internal static string PLACEHOLDER_EMERGENCYCONTACT1_FAMILYRELATIONSHIP {
            get {
                return ResourceManager.GetString("PLACEHOLDER_EMERGENCYCONTACT1_FAMILYRELATIONSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martha Wayne.
        /// </summary>
        internal static string PLACEHOLDER_EMERGENCYCONTACT1_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_EMERGENCYCONTACT1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        internal static string PLACEHOLDER_EMERGENCYCONTACT2_FAMILYRELATIONSHIP {
            get {
                return ResourceManager.GetString("PLACEHOLDER_EMERGENCYCONTACT2_FAMILYRELATIONSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thomas Wayne.
        /// </summary>
        internal static string PLACEHOLDER_EMERGENCYCONTACT2_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_EMERGENCYCONTACT2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string PLACEHOLDER_MANUFACTURER {
            get {
                return ResourceManager.GetString("PLACEHOLDER_MANUFACTURER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruce Wayne.
        /// </summary>
        internal static string PLACEHOLDER_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palisades.
        /// </summary>
        internal static string PLACEHOLDER_NEIGHBORHOOD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_NEIGHBORHOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network&apos;s name ....
        /// </summary>
        internal static string PLACEHOLDER_NETWORK_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_NETWORK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string PLACEHOLDER_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PLACEHOLDER_PASSWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation password.
        /// </summary>
        internal static string PLACEHOLDER_PASSWORD_CONFIRMATION {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PASSWORD_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (31) 9 0000-0000 .
        /// </summary>
        internal static string PLACEHOLDER_PHONENUMBER {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PHONENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string PLACEHOLDER_PRODUCT {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.275-972.
        /// </summary>
        internal static string PLACEHOLDER_ZIPCODE {
            get {
                return ResourceManager.GetString("PLACEHOLDER_ZIPCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection!.
        /// </summary>
        internal static string TEXT_CHECK_YOUR_INTERNET_CONNECTION {
            get {
                return ResourceManager.GetString("TEXT_CHECK_YOUR_INTERNET_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the App.
        /// </summary>
        internal static string TITILE_ABOUT_APP {
            get {
                return ResourceManager.GetString("TITILE_ABOUT_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friend.
        /// </summary>
        internal static string TITLE_ADD_FRIEND {
            get {
                return ResourceManager.GetString("TITLE_ADD_FRIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product.
        /// </summary>
        internal static string TITLE_ADD_PRODUCT {
            get {
                return ResourceManager.GetString("TITLE_ADD_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now the address.
        /// </summary>
        internal static string TITLE_ADDRESS {
            get {
                return ResourceManager.GetString("TITLE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string TITLE_ADDRESS_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_ADDRESS_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any complement?.
        /// </summary>
        internal static string TITLE_ADDRESSCOMPLEMENT {
            get {
                return ResourceManager.GetString("TITLE_ADDRESSCOMPLEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complement:.
        /// </summary>
        internal static string TITLE_ADDRESSCOMPLEMENT_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_ADDRESSCOMPLEMENT_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the number?.
        /// </summary>
        internal static string TITLE_ADDRESSNUMBER {
            get {
                return ResourceManager.GetString("TITLE_ADDRESSNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number:.
        /// </summary>
        internal static string TITLE_ADDRESSNUMBER_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_ADDRESSNUMBER_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        internal static string TITLE_AMOUNT_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_AMOUNT_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string TITLE_AND {
            get {
                return ResourceManager.GetString("TITLE_AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the camera closer to the QRCode to read..
        /// </summary>
        internal static string TITLE_APPROACH_CAMERA_READ_QRCODE {
            get {
                return ResourceManager.GetString("TITLE_APPROACH_CAMERA_READ_QRCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box(es).
        /// </summary>
        internal static string TITLE_BOX {
            get {
                return ResourceManager.GetString("TITLE_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to {0}:.
        /// </summary>
        internal static string TITLE_CALL_TO_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CALL_TO_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TITLE_CANCEL {
            get {
                return ResourceManager.GetString("TITLE_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string TITLE_CHANGE {
            get {
                return ResourceManager.GetString("TITLE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change joined date.
        /// </summary>
        internal static string TITLE_CHANGE_JOINED_DATE {
            get {
                return ResourceManager.GetString("TITLE_CHANGE_JOINED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string TITLE_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one of the numbers below:.
        /// </summary>
        internal static string TITLE_CHOOSE_ONE_NUMBERS_BELOW_TOWPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CHOOSE_ONE_NUMBERS_BELOW_TOWPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your friend.
        /// </summary>
        internal static string TITLE_CHOOSE_YOUR_FRIEND {
            get {
                return ResourceManager.GetString("TITLE_CHOOSE_YOUR_FRIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string TITLE_CITY_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CITY_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean house.
        /// </summary>
        internal static string TITLE_CLEAN_HOUSE {
            get {
                return ResourceManager.GetString("TITLE_CLEAN_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code received:.
        /// </summary>
        internal static string TITLE_CODE_RECEIVED_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CODE_RECEIVED_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conclude.
        /// </summary>
        internal static string TITLE_CONCLUDE {
            get {
                return ResourceManager.GetString("TITLE_CONCLUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinship with contact 1:.
        /// </summary>
        internal static string TITLE_CONTACT_EMERGENCY_1_DEGREE_KINSHIP_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_EMERGENCY_1_DEGREE_KINSHIP_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact&apos;s 1 phone number:.
        /// </summary>
        internal static string TITLE_CONTACT_EMERGENCY_1_PHONENUMBER_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_EMERGENCY_1_PHONENUMBER_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 1:.
        /// </summary>
        internal static string TITLE_CONTACT_EMERGENCY_1_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_EMERGENCY_1_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinship with contact 2:.
        /// </summary>
        internal static string TITLE_CONTACT_EMERGENCY_2_DEGREE_KINSHIP_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_EMERGENCY_2_DEGREE_KINSHIP_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact&apos;s 2 phone number:.
        /// </summary>
        internal static string TITLE_CONTACT_EMERGENCY_2_PHONENUMBER_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_EMERGENCY_2_PHONENUMBER_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 2:.
        /// </summary>
        internal static string TITLE_CONTACT_EMERGENCY_2_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_EMERGENCY_2_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me an emergency contact.
        /// </summary>
        internal static string TITLE_CONTACT_EMERGENCY_CASES {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_EMERGENCY_CASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you wish, you can inform me of a second emergency contact (optional).
        /// </summary>
        internal static string TITLE_CONTACT_EMERGENCY_CASES_OPTIONAL {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_EMERGENCY_CASES_OPTIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a home.
        /// </summary>
        internal static string TITLE_CREATE_HOME {
            get {
                return ResourceManager.GetString("TITLE_CREATE_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password:.
        /// </summary>
        internal static string TITLE_CURRENT_PASSWORD_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CURRENT_PASSWORD_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string TITLE_DAY {
            get {
                return ResourceManager.GetString("TITLE_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string TITLE_DAYS {
            get {
                return ResourceManager.GetString("TITLE_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string TITLE_DELETE {
            get {
                return ResourceManager.GetString("TITLE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        internal static string TITLE_DELETE_ACCOUNT {
            get {
                return ResourceManager.GetString("TITLE_DELETE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete home.
        /// </summary>
        internal static string TITLE_DELETE_HOME {
            get {
                return ResourceManager.GetString("TITLE_DELETE_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date:.
        /// </summary>
        internal static string TITLE_DUEDATE_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_DUEDATE_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string TITLE_EDIT {
            get {
                return ResourceManager.GetString("TITLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the email to recover the password?.
        /// </summary>
        internal static string TITLE_EMAIL_RECOVER_PASSAWORD {
            get {
                return ResourceManager.GetString("TITLE_EMAIL_RECOVER_PASSAWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        internal static string TITLE_EMAIL_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_EMAIL_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency contacts:.
        /// </summary>
        internal static string TITLE_EMERGENCY_CONTACTS_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_EMERGENCY_CONTACTS_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finances.
        /// </summary>
        internal static string TITLE_FINANCES {
            get {
                return ResourceManager.GetString("TITLE_FINANCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string TITLE_FORGOT_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_FORGOT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frid.
        /// </summary>
        internal static string TITLE_FRIDAY_ABBREVIATED {
            get {
                return ResourceManager.GetString("TITLE_FRIDAY_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} friends available..
        /// </summary>
        internal static string TITLE_FRIENDS_AVALIABLE {
            get {
                return ResourceManager.GetString("TITLE_FRIENDS_AVALIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating code ....
        /// </summary>
        internal static string TITLE_GENERATING_CODE {
            get {
                return ResourceManager.GetString("TITLE_GENERATING_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home, sweet home.
        /// </summary>
        internal static string TITLE_HOME_SWEET_HOME {
            get {
                return ResourceManager.GetString("TITLE_HOME_SWEET_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s so sad see you go :((.
        /// </summary>
        internal static string TITLE_ITISSAD_SEEYOUGO {
            get {
                return ResourceManager.GetString("TITLE_ITISSAD_SEEYOUGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join a home.
        /// </summary>
        internal static string TITLE_JOIN_HOME {
            get {
                return ResourceManager.GetString("TITLE_JOIN_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined on {0}.
        /// </summary>
        internal static string TITLE_JOINED_ON {
            get {
                return ResourceManager.GetString("TITLE_JOINED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogram(s).
        /// </summary>
        internal static string TITLE_KILOGRAM {
            get {
                return ResourceManager.GetString("TITLE_KILOGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to continue.
        /// </summary>
        internal static string TITLE_LOGIN_TO_CONTINUE {
            get {
                return ResourceManager.GetString("TITLE_LOGIN_TO_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer:.
        /// </summary>
        internal static string TITLE_MANUFACTURER_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_MANUFACTURER_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        internal static string TITLE_MONDAY_ABBREVIATED {
            get {
                return ResourceManager.GetString("TITLE_MONDAY_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        internal static string TITLE_MONTH {
            get {
                return ResourceManager.GetString("TITLE_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string TITLE_MONTHS {
            get {
                return ResourceManager.GetString("TITLE_MONTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My foods.
        /// </summary>
        internal static string TITLE_MY_FOODS {
            get {
                return ResourceManager.GetString("TITLE_MY_FOODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My friends.
        /// </summary>
        internal static string TITLE_MY_FRIENDS {
            get {
                return ResourceManager.GetString("TITLE_MY_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My informations.
        /// </summary>
        internal static string TITLE_MY_INFORMATIONS {
            get {
                return ResourceManager.GetString("TITLE_MY_INFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string TITLE_NAME_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_NAME_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Neighborhood.
        /// </summary>
        internal static string TITLE_NEIGHBORHOOD {
            get {
                return ResourceManager.GetString("TITLE_NEIGHBORHOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighborhood:.
        /// </summary>
        internal static string TITLE_NEIGHBORHOOD_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_NEIGHBORHOOD_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New item.
        /// </summary>
        internal static string TITLE_NEW_ITEM {
            get {
                return ResourceManager.GetString("TITLE_NEW_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password:.
        /// </summary>
        internal static string TITLE_NEW_PASSWORD_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_NEW_PASSWORD_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string TITLE_NEXT {
            get {
                return ResourceManager.GetString("TITLE_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify that an order has arrived :).
        /// </summary>
        internal static string TITLE_NOTIFY_ORDER_ARRIVED {
            get {
                return ResourceManager.GetString("TITLE_NOTIFY_ORDER_ARRIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now your phone number.
        /// </summary>
        internal static string TITLE_NOW_YOUR_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("TITLE_NOW_YOUR_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package(s).
        /// </summary>
        internal static string TITLE_PACKAGE {
            get {
                return ResourceManager.GetString("TITLE_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirmation:.
        /// </summary>
        internal static string TITLE_PASSWORD_CONFIRMATION_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_PASSWORD_CONFIRMATION_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string TITLE_PASSWORD_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_PASSWORD_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number 1:.
        /// </summary>
        internal static string TITLE_PHONENUMBER_1_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_PHONENUMBER_1_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number 2:.
        /// </summary>
        internal static string TITLE_PHONENUMBER_2_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_PHONENUMBER_2_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonenumber:.
        /// </summary>
        internal static string TITLE_PHONENUMBER_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_PHONENUMBER_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For security reasons, please log in again..
        /// </summary>
        internal static string TITLE_PLEASE_LOGIN_AGAIN {
            get {
                return ResourceManager.GetString("TITLE_PLEASE_LOGIN_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product:.
        /// </summary>
        internal static string TITLE_PRODUCT_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_PRODUCT_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} products avaliables.
        /// </summary>
        internal static string TITLE_PRODUCTS_AVALIABLES {
            get {
                return ResourceManager.GetString("TITLE_PRODUCTS_AVALIABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string TITLE_REGISTER {
            get {
                return ResourceManager.GetString("TITLE_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To finish :) Wi-fi network information.
        /// </summary>
        internal static string TITLE_REGISTER_NETWORK_INFORMATION {
            get {
                return ResourceManager.GetString("TITLE_REGISTER_NETWORK_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship:.
        /// </summary>
        internal static string TITLE_RELATIONSHIP_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_RELATIONSHIP_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string TITLE_REMOVE {
            get {
                return ResourceManager.GetString("TITLE_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string TITLE_RETURN {
            get {
                return ResourceManager.GetString("TITLE_RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        internal static string TITLE_SATURDAY_ABBREVIATED {
            get {
                return ResourceManager.GetString("TITLE_SATURDAY_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string TITLE_SAVE {
            get {
                return ResourceManager.GetString("TITLE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and new.
        /// </summary>
        internal static string TITLE_SAVE_AND_NEW {
            get {
                return ResourceManager.GetString("TITLE_SAVE_AND_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name.
        /// </summary>
        internal static string TITLE_SEARCH_BY_NAME {
            get {
                return ResourceManager.GetString("TITLE_SEARCH_BY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as administrator.
        /// </summary>
        internal static string TITLE_SET_AS_ADMINISTRATOR {
            get {
                return ResourceManager.GetString("TITLE_SET_AS_ADMINISTRATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        internal static string TITLE_SHOPPING {
            get {
                return ResourceManager.GetString("TITLE_SHOPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        internal static string TITLE_SUNDAY_ABBREVIATED {
            get {
                return ResourceManager.GetString("TITLE_SUNDAY_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me the Zip Code :).
        /// </summary>
        internal static string TITLE_TELLME_ZIPCODE {
            get {
                return ResourceManager.GetString("TITLE_TELLME_ZIPCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City is:.
        /// </summary>
        internal static string TITLE_THE_CITY_IS {
            get {
                return ResourceManager.GetString("TITLE_THE_CITY_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will expire in:.
        /// </summary>
        internal static string TITLE_THIS_OPERATION_WILL_EXPIRE {
            get {
                return ResourceManager.GetString("TITLE_THIS_OPERATION_WILL_EXPIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        internal static string TITLE_THURSDAY_ABBREVIATED {
            get {
                return ResourceManager.GetString("TITLE_THURSDAY_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time has expired. Please try again..
        /// </summary>
        internal static string TITLE_TIME_EXPIRED_TRY_AGAIN {
            get {
                return ResourceManager.GetString("TITLE_TIME_EXPIRED_TRY_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To finish. Your password.
        /// </summary>
        internal static string TITLE_TO_FINISH_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_TO_FINISH_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To begin :) Tell me what is your e-mail.
        /// </summary>
        internal static string TITLE_TOBEGIN_TELL_EMAIL {
            get {
                return ResourceManager.GetString("TITLE_TOBEGIN_TELL_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch the screen to focus..
        /// </summary>
        internal static string TITLE_TOUCH_SCREEN_TO_FOCUS {
            get {
                return ResourceManager.GetString("TITLE_TOUCH_SCREEN_TO_FOCUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        internal static string TITLE_TUESDAY_ABBREVIATED {
            get {
                return ResourceManager.GetString("TITLE_TUESDAY_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string TITLE_TYPE_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_TYPE_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity(s).
        /// </summary>
        internal static string TITLE_UNITY {
            get {
                return ResourceManager.GetString("TITLE_UNITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string TITLE_VERSION {
            get {
                return ResourceManager.GetString("TITLE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        internal static string TITLE_WEDNESDAY_ABBREVIATED {
            get {
                return ResourceManager.GetString("TITLE_WEDNESDAY_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome :).
        /// </summary>
        internal static string TITLE_WELCOME {
            get {
                return ResourceManager.GetString("TITLE_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        internal static string TITLE_YEAR {
            get {
                return ResourceManager.GetString("TITLE_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        internal static string TITLE_YEARS {
            get {
                return ResourceManager.GetString("TITLE_YEARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I&apos;m sure.
        /// </summary>
        internal static string TITLE_YES_IAMSURE {
            get {
                return ResourceManager.GetString("TITLE_YES_IAMSURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name ;).
        /// </summary>
        internal static string TITLE_YOUR_NAME {
            get {
                return ResourceManager.GetString("TITLE_YOUR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCode:.
        /// </summary>
        internal static string TITLE_ZIPCODE_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_ZIPCODE_TWOPOINTS", resourceCulture);
            }
        }
    }
}
