//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentHabitacion.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntelligentHabitacion.App.ResourceText", typeof(ResourceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application was created with the intention of making life easier for people who share an apartment with friends..
        /// </summary>
        internal static string ABOUT_APP_FIRST_PART {
            get {
                return ResourceManager.GetString("ABOUT_APP_FIRST_PART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The App will assist in organizing and sending notifications for important matters, such as: notifications to remember the cleaning schedule; on the payment of the rent; notice of receipt of orders, and others..
        /// </summary>
        internal static string ABOUT_APP_SECOND_PART {
            get {
                return ResourceManager.GetString("ABOUT_APP_SECOND_PART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With an easy and creative design, I hope it will be useful for your home :).
        /// </summary>
        internal static string ABOUT_APP_THIRD_PART {
            get {
                return ResourceManager.GetString("ABOUT_APP_THIRD_PART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        internal static string AUSTRALIA {
            get {
                return ResourceManager.GetString("AUSTRALIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium.
        /// </summary>
        internal static string BELGIUM {
            get {
                return ResourceManager.GetString("BELGIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil.
        /// </summary>
        internal static string BRAZIL {
            get {
                return ResourceManager.GetString("BRAZIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        internal static string CANADA {
            get {
                return ResourceManager.GetString("CANADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a country below:.
        /// </summary>
        internal static string CHOOSE_A_COUNTRY_BELOW {
            get {
                return ResourceManager.GetString("CHOOSE_A_COUNTRY_BELOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By performing this process you are transferring all the privileges of being an Administrator to your friend.
        /// </summary>
        internal static string DESCRIPTION_ACTION_CHANGE_ADMINISTRATOR {
            get {
                return ResourceManager.GetString("DESCRIPTION_ACTION_CHANGE_ADMINISTRATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will be removed from association with Home. However, histories such as: payments, cleaning schedule, etc., will be stored for future consultations..
        /// </summary>
        internal static string DESCRIPTION_ACTION_REMOVE_FRIEND_FROM_HOME {
            get {
                return ResourceManager.GetString("DESCRIPTION_ACTION_REMOVE_FRIEND_FROM_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new member must go to the app, click on “Join a home” and read the QR Code below :).
        /// </summary>
        internal static string DESCRIPTION_ADDING_FRIEND {
            get {
                return ResourceManager.GetString("DESCRIPTION_ADDING_FRIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  all .
        /// </summary>
        internal static string DESCRIPTION_ALL {
            get {
                return ResourceManager.GetString("DESCRIPTION_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below you can choose one or more rooms to be cleaned in the month..
        /// </summary>
        internal static string DESCRIPTION_CHOOSE_ROOMS_TO_BE_CLEANED {
            get {
                return ResourceManager.GetString("DESCRIPTION_CHOOSE_ROOMS_TO_BE_CLEANED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow the Cleaning schedule to make the home clean and beautiful..
        /// </summary>
        internal static string DESCRIPTION_CLEAN_HOUSE {
            get {
                return ResourceManager.GetString("DESCRIPTION_CLEAN_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to create a home and be the administrator..
        /// </summary>
        internal static string DESCRIPTION_CREATE_HOME {
            get {
                return ResourceManager.GetString("DESCRIPTION_CREATE_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning performed on {0} ({1}) by {2}.
        /// </summary>
        internal static string DESCRIPTION_DATE_CLEANING_BY_FRIEND {
            get {
                return ResourceManager.GetString("DESCRIPTION_DATE_CLEANING_BY_FRIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENTION!!! Continuing with this process will result in the loss of .
        /// </summary>
        internal static string DESCRIPTION_DELETE_HOME_FIRST_PHRASE {
            get {
                return ResourceManager.GetString("DESCRIPTION_DELETE_HOME_FIRST_PHRASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  possible to recover data after confirming this process..
        /// </summary>
        internal static string DESCRIPTION_DELETE_HOME_FOURTH_PHRASE {
            get {
                return ResourceManager.GetString("DESCRIPTION_DELETE_HOME_FOURTH_PHRASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information from Home, including history such as: payments, cleaning schedule, etc..
        /// </summary>
        internal static string DESCRIPTION_DELETE_HOME_SECOND_PHRASE {
            get {
                return ResourceManager.GetString("DESCRIPTION_DELETE_HOME_SECOND_PHRASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember, .
        /// </summary>
        internal static string DESCRIPTION_DELETE_HOME_THIRD_PHRASE {
            get {
                return ResourceManager.GetString("DESCRIPTION_DELETE_HOME_THIRD_PHRASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track your household income and expenses..
        /// </summary>
        internal static string DESCRIPTION_FINANCES {
            get {
                return ResourceManager.GetString("DESCRIPTION_FINANCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See useful information about home data..
        /// </summary>
        internal static string DESCRIPTION_HOME_SWEET_HOME {
            get {
                return ResourceManager.GetString("DESCRIPTION_HOME_SWEET_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below you can see which rooms in the house were cleaned, who cleaned and on which days of the selected month..
        /// </summary>
        internal static string DESCRIPTION_HOUSEWORK {
            get {
                return ResourceManager.GetString("DESCRIPTION_HOUSEWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to be part of a home already created..
        /// </summary>
        internal static string DESCRIPTION_JOIN_HOME {
            get {
                return ResourceManager.GetString("DESCRIPTION_JOIN_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the tasks for each of the household&apos;s residents. Don&apos;t worry, you can change this whenever you want :).
        /// </summary>
        internal static string DESCRIPTION_MANAGE_SCHEDULE {
            get {
                return ResourceManager.GetString("DESCRIPTION_MANAGE_SCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track the foods you have, with quantity and expiration date..
        /// </summary>
        internal static string DESCRIPTION_MY_FOOD {
            get {
                return ResourceManager.GetString("DESCRIPTION_MY_FOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See useful information about your friends at home..
        /// </summary>
        internal static string DESCRIPTION_MY_FRIENDS {
            get {
                return ResourceManager.GetString("DESCRIPTION_MY_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to see and/or edit your registry information..
        /// </summary>
        internal static string DESCRIPTION_MY_INFORMATIONS {
            get {
                return ResourceManager.GetString("DESCRIPTION_MY_INFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below you will find information about your tasks performed each month :).
        /// </summary>
        internal static string DESCRIPTION_MY_TASKS_CLEANHOUSE {
            get {
                return ResourceManager.GetString("DESCRIPTION_MY_TASKS_CLEANHOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will send a notification to let {0} know that an order has arrived. Do you confirm this?.
        /// </summary>
        internal static string DESCRIPTION_NOTIFY_ORDER_ARRIVED {
            get {
                return ResourceManager.GetString("DESCRIPTION_NOTIFY_ORDER_ARRIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your friends will receive a notification and can evaluate your work. Do you confirm this?.
        /// </summary>
        internal static string DESCRIPTION_ROOM_CLEANED {
            get {
                return ResourceManager.GetString("DESCRIPTION_ROOM_CLEANED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below you will find information on the tasks performed each month :).
        /// </summary>
        internal static string DESCRIPTION_SCHEDULE_CLEAR_HOUSE {
            get {
                return ResourceManager.GetString("DESCRIPTION_SCHEDULE_CLEAR_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to the Supermarket? Take a look at the shopping list..
        /// </summary>
        internal static string DESCRIPTION_SHOPPING {
            get {
                return ResourceManager.GetString("DESCRIPTION_SHOPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Home Address is available ONLY to people who live in the same home as you. Wi-fi information too. The goal is to make it easier for residents to obtain information quickly and simply. Your friend can check the address to buy the new MAC and use the Wi-Fi information to connect it to the network :).
        /// </summary>
        internal static string DESCRIPTION_WHY_WE_NEED_YOUR_ADDRESS {
            get {
                return ResourceManager.GetString("DESCRIPTION_WHY_WE_NEED_YOUR_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here the zip code is important to help fill in the address in the next step. The Home Address is available ONLY to people who live in the same home as you..
        /// </summary>
        internal static string DESCRIPTION_WHY_WE_NEED_YOUR_CEP {
            get {
                return ResourceManager.GetString("DESCRIPTION_WHY_WE_NEED_YOUR_CEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email will be used to login to the App and through it we can send you links to recover your password, security codes for you to delete important information, etc. HEY, we will send you ONLY important content, so don&apos;t worry :).
        /// </summary>
        internal static string DESCRIPTION_WHY_WE_NEED_YOUR_EMAIL {
            get {
                return ResourceManager.GetString("DESCRIPTION_WHY_WE_NEED_YOUR_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This information will ONLY be shared with people who live in the same home as you. The goal is to help your friends communicate with someone important to you in case something unforeseen happens..
        /// </summary>
        internal static string DESCRIPTION_WHY_WE_NEED_YOUR_EMERGENCY_CONTACT {
            get {
                return ResourceManager.GetString("DESCRIPTION_WHY_WE_NEED_YOUR_EMERGENCY_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone will ONLY be shared with people who live in the same home as you. The intention is to facilitate communication between residents..
        /// </summary>
        internal static string DESCRIPTION_WHY_WE_NEED_YOUR_TELEPHONE_NUMBER {
            get {
                return ResourceManager.GetString("DESCRIPTION_WHY_WE_NEED_YOUR_TELEPHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t worry, your name will not be displayed in the rating when your friend views it :).
        /// </summary>
        internal static string DESCRIPTION_YOUR_EVALUATION {
            get {
                return ResourceManager.GetString("DESCRIPTION_YOUR_EVALUATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has arrived and is waiting for you ;).
        /// </summary>
        internal static string DESCRIPTION_YOUR_ORDER_HAS_ARRIVED_WAINTING_FOR_YOU {
            get {
                return ResourceManager.GetString("DESCRIPTION_YOUR_ORDER_HAS_ARRIVED_WAINTING_FOR_YOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for the schedule settings, right? At this time, the schedule will be automatically set every 1st of every month. But don&apos;t worry, the administrator will have full control over this configuration very soon :).
        /// </summary>
        internal static string DESCRITION_SETTINGS_SCHEDULE_CLEAN_HOUSE {
            get {
                return ResourceManager.GetString("DESCRITION_SETTINGS_SCHEDULE_CLEAN_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMMM dd, yyyy.
        /// </summary>
        internal static string FORMAT_DATE {
            get {
                return ResourceManager.GetString("FORMAT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        internal static string FRANCE {
            get {
                return ResourceManager.GetString("FRANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong.
        /// </summary>
        internal static string HONG_KONG {
            get {
                return ResourceManager.GetString("HONG_KONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password copied successfully.
        /// </summary>
        internal static string INFORMATION_PASSWORD_COPIED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("INFORMATION_PASSWORD_COPIED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot perform this action for now..
        /// </summary>
        internal static string INFORMATION_YOU_CAN_NOT_PERFORM_THIS_ACTION {
            get {
                return ResourceManager.GetString("INFORMATION_YOU_CAN_NOT_PERFORM_THIS_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ireland.
        /// </summary>
        internal static string IRELAND {
            get {
                return ResourceManager.GetString("IRELAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        internal static string ITALY {
            get {
                return ResourceManager.GetString("ITALY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        internal static string JAPAN {
            get {
                return ResourceManager.GetString("JAPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg.
        /// </summary>
        internal static string LUXEMBOURG {
            get {
                return ResourceManager.GetString("LUXEMBOURG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maldives.
        /// </summary>
        internal static string MALDIVES {
            get {
                return ResourceManager.GetString("MALDIVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico.
        /// </summary>
        internal static string MEXICO {
            get {
                return ResourceManager.GetString("MEXICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monaco.
        /// </summary>
        internal static string MONACO {
            get {
                return ResourceManager.GetString("MONACO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands.
        /// </summary>
        internal static string NETHERLANDS {
            get {
                return ResourceManager.GetString("NETHERLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand.
        /// </summary>
        internal static string NEW_ZEALAND {
            get {
                return ResourceManager.GetString("NEW_ZEALAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to perform this action?.
        /// </summary>
        internal static string PHRASE_AREYOUSUREEXCUTETHISACTION {
            get {
                return ResourceManager.GetString("PHRASE_AREYOUSUREEXCUTETHISACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the button below to add the products. So we can help you with expiration date, quantity, etc. :).
        /// </summary>
        internal static string PHRASE_YOU_HAVENT_ADDED_FOODS {
            get {
                return ResourceManager.GetString("PHRASE_YOU_HAVENT_ADDED_FOODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh no, you haven&apos;t added any friends yet :(.
        /// </summary>
        internal static string PHRASE_YOU_HAVENT_ADDED_FRIENDS {
            get {
                return ResourceManager.GetString("PHRASE_YOU_HAVENT_ADDED_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional address.
        /// </summary>
        internal static string PLACEHOLDER_ADDITIONALADDRESSINFO {
            get {
                return ResourceManager.GetString("PLACEHOLDER_ADDITIONALADDRESSINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street/Avenue.
        /// </summary>
        internal static string PLACEHOLDER_ADDRESS {
            get {
                return ResourceManager.GetString("PLACEHOLDER_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string PLACEHOLDER_ADDRESSNUMBER {
            get {
                return ResourceManager.GetString("PLACEHOLDER_ADDRESSNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string PLACEHOLDER_CITY {
            get {
                return ResourceManager.GetString("PLACEHOLDER_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code received in email.
        /// </summary>
        internal static string PLACEHOLDER_CODE_RECEIVED {
            get {
                return ResourceManager.GetString("PLACEHOLDER_CODE_RECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string PLACEHOLDER_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline for payment of rent (between days 1 and 28).
        /// </summary>
        internal static string PLACEHOLDER_DEADLINE_PAYMENT_RENT {
            get {
                return ResourceManager.GetString("PLACEHOLDER_DEADLINE_PAYMENT_RENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        internal static string PLACEHOLDER_DUE_DATE {
            get {
                return ResourceManager.GetString("PLACEHOLDER_DUE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bruce@waynetech.com.
        /// </summary>
        internal static string PLACEHOLDER_EMAIL {
            get {
                return ResourceManager.GetString("PLACEHOLDER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family relationship. E.g.: Mother, sister ....
        /// </summary>
        internal static string PLACEHOLDER_EMERGENCYCONTACT1_FAMILYRELATIONSHIP {
            get {
                return ResourceManager.GetString("PLACEHOLDER_EMERGENCYCONTACT1_FAMILYRELATIONSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name. E.g.: Martha Wayne.
        /// </summary>
        internal static string PLACEHOLDER_EMERGENCYCONTACT1_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_EMERGENCYCONTACT1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family relationship. E.g.: Father, brother ....
        /// </summary>
        internal static string PLACEHOLDER_EMERGENCYCONTACT2_FAMILYRELATIONSHIP {
            get {
                return ResourceManager.GetString("PLACEHOLDER_EMERGENCYCONTACT2_FAMILYRELATIONSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name. E.g.: Thomas Wayne.
        /// </summary>
        internal static string PLACEHOLDER_EMERGENCYCONTACT2_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_EMERGENCYCONTACT2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry date.
        /// </summary>
        internal static string PLACEHOLDER_ENTRY_DATE {
            get {
                return ResourceManager.GetString("PLACEHOLDER_ENTRY_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Relationship.
        /// </summary>
        internal static string PLACEHOLDER_FAMILYRELATIONSHIP {
            get {
                return ResourceManager.GetString("PLACEHOLDER_FAMILYRELATIONSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string PLACEHOLDER_MANUFACTURER {
            get {
                return ResourceManager.GetString("PLACEHOLDER_MANUFACTURER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600.00.
        /// </summary>
        internal static string PLACEHOLDER_MONTHLYRENT {
            get {
                return ResourceManager.GetString("PLACEHOLDER_MONTHLYRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruce Wayne.
        /// </summary>
        internal static string PLACEHOLDER_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighborhood.
        /// </summary>
        internal static string PLACEHOLDER_NEIGHBORHOOD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_NEIGHBORHOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network&apos;s name ....
        /// </summary>
        internal static string PLACEHOLDER_NETWORK_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_NETWORK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string PLACEHOLDER_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PLACEHOLDER_PASSWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation password.
        /// </summary>
        internal static string PLACEHOLDER_PASSWORD_CONFIRMATION {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PASSWORD_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 (555) 555-1234.
        /// </summary>
        internal static string PLACEHOLDER_PHONENUMBER {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PHONENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string PLACEHOLDER_PRODUCT {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string PLACEHOLDER_QUANTITY {
            get {
                return ResourceManager.GetString("PLACEHOLDER_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        internal static string PLACEHOLDER_RELATIONSHIP {
            get {
                return ResourceManager.GetString("PLACEHOLDER_RELATIONSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen.
        /// </summary>
        internal static string PLACEHOLDER_ROOM {
            get {
                return ResourceManager.GetString("PLACEHOLDER_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string PLACEHOLDER_STATE {
            get {
                return ResourceManager.GetString("PLACEHOLDER_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal.
        /// </summary>
        internal static string PORTUGAL {
            get {
                return ResourceManager.GetString("PORTUGAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto Rico.
        /// </summary>
        internal static string PUERTO_RICO {
            get {
                return ResourceManager.GetString("PUERTO_RICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        internal static string RUSSIA {
            get {
                return ResourceManager.GetString("RUSSIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        internal static string SPAIN {
            get {
                return ResourceManager.GetString("SPAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try another filter :).
        /// </summary>
        internal static string SUBTITLE_NO_RESULTS_MATCHED_FILTER {
            get {
                return ResourceManager.GetString("SUBTITLE_NO_RESULTS_MATCHED_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        internal static string SWITZERLAND {
            get {
                return ResourceManager.GetString("SWITZERLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection!.
        /// </summary>
        internal static string TEXT_CHECK_YOUR_INTERNET_CONNECTION {
            get {
                return ResourceManager.GetString("TEXT_CHECK_YOUR_INTERNET_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the App.
        /// </summary>
        internal static string TITILE_ABOUT_APP {
            get {
                return ResourceManager.GetString("TITILE_ABOUT_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string TITLE_ACCEPT {
            get {
                return ResourceManager.GetString("TITLE_ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted!.
        /// </summary>
        internal static string TITLE_ACCEPTED {
            get {
                return ResourceManager.GetString("TITLE_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friend.
        /// </summary>
        internal static string TITLE_ADD_FRIEND {
            get {
                return ResourceManager.GetString("TITLE_ADD_FRIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product.
        /// </summary>
        internal static string TITLE_ADD_PRODUCT {
            get {
                return ResourceManager.GetString("TITLE_ADD_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a room.
        /// </summary>
        internal static string TITLE_ADD_ROOM {
            get {
                return ResourceManager.GetString("TITLE_ADD_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Rooms in the house.
        /// </summary>
        internal static string TITLE_ADD_ROOMS_HOME {
            get {
                return ResourceManager.GetString("TITLE_ADD_ROOMS_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new Friend.
        /// </summary>
        internal static string TITLE_ADDING_NEW_FRIEND {
            get {
                return ResourceManager.GetString("TITLE_ADDING_NEW_FRIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional address info:.
        /// </summary>
        internal static string TITLE_ADDITIONALADDRESSINFO_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_ADDITIONALADDRESSINFO_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string TITLE_ADDRESS {
            get {
                return ResourceManager.GetString("TITLE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string TITLE_ADDRESS_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_ADDRESS_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number:.
        /// </summary>
        internal static string TITLE_ADDRESSNUMBER_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_ADDRESSNUMBER_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Administrator must configure the cleaning schedule..
        /// </summary>
        internal static string TITLE_ADMINISTRATOR_MUST_CONFIGURE_CLEANING_SCHEDULE {
            get {
                return ResourceManager.GetString("TITLE_ADMINISTRATOR_MUST_CONFIGURE_CLEANING_SCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, I received!.
        /// </summary>
        internal static string TITLE_ALREADY_RECEIVED {
            get {
                return ResourceManager.GetString("TITLE_ALREADY_RECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string TITLE_AND {
            get {
                return ResourceManager.GetString("TITLE_AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the camera closer to the QRCode to read..
        /// </summary>
        internal static string TITLE_APPROACH_CAMERA_READ_QRCODE {
            get {
                return ResourceManager.GetString("TITLE_APPROACH_CAMERA_READ_QRCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign tasks.
        /// </summary>
        internal static string TITLE_ASSIGN_TASKS {
            get {
                return ResourceManager.GetString("TITLE_ASSIGN_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathroom.
        /// </summary>
        internal static string TITLE_BATHROOM {
            get {
                return ResourceManager.GetString("TITLE_BATHROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box(es).
        /// </summary>
        internal static string TITLE_BOX {
            get {
                return ResourceManager.GetString("TITLE_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to {0}:.
        /// </summary>
        internal static string TITLE_CALL_TO_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CALL_TO_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TITLE_CANCEL {
            get {
                return ResourceManager.GetString("TITLE_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel operation.
        /// </summary>
        internal static string TITLE_CANCEL_OPERATION {
            get {
                return ResourceManager.GetString("TITLE_CANCEL_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string TITLE_CHANGE {
            get {
                return ResourceManager.GetString("TITLE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change joined date.
        /// </summary>
        internal static string TITLE_CHANGE_JOINED_DATE {
            get {
                return ResourceManager.GetString("TITLE_CHANGE_JOINED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string TITLE_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking E-mail ....
        /// </summary>
        internal static string TITLE_CHECKING_EMAIL {
            get {
                return ResourceManager.GetString("TITLE_CHECKING_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one of the numbers below:.
        /// </summary>
        internal static string TITLE_CHOOSE_ONE_NUMBERS_BELOW_TOWPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CHOOSE_ONE_NUMBERS_BELOW_TOWPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the room(s):.
        /// </summary>
        internal static string TITLE_CHOOSE_THE_ROOMS_TWO_POINTS {
            get {
                return ResourceManager.GetString("TITLE_CHOOSE_THE_ROOMS_TWO_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your friend.
        /// </summary>
        internal static string TITLE_CHOOSE_YOUR_FRIEND {
            get {
                return ResourceManager.GetString("TITLE_CHOOSE_YOUR_FRIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your rating from 1 to 5 stars;).
        /// </summary>
        internal static string TITLE_CHOOSE_YOUR_RATING {
            get {
                return ResourceManager.GetString("TITLE_CHOOSE_YOUR_RATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string TITLE_CITY_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CITY_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean house.
        /// </summary>
        internal static string TITLE_CLEAN_HOUSE {
            get {
                return ResourceManager.GetString("TITLE_CLEAN_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning records: {0}.
        /// </summary>
        internal static string TITLE_CLEANING_RECORDS {
            get {
                return ResourceManager.GetString("TITLE_CLEANING_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code received:.
        /// </summary>
        internal static string TITLE_CODE_RECEIVED_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CODE_RECEIVED_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string TITLE_COMMENT {
            get {
                return ResourceManager.GetString("TITLE_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed today.
        /// </summary>
        internal static string TITLE_COMPLETED_TODAY {
            get {
                return ResourceManager.GetString("TITLE_COMPLETED_TODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conclude.
        /// </summary>
        internal static string TITLE_CONCLUDE {
            get {
                return ResourceManager.GetString("TITLE_CONCLUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Relationship to contact 1:.
        /// </summary>
        internal static string TITLE_CONTACT_EMERGENCY_1_FAMILYRELATIONSHIP_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_EMERGENCY_1_FAMILYRELATIONSHIP_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact&apos;s 1 phone number:.
        /// </summary>
        internal static string TITLE_CONTACT_EMERGENCY_1_PHONENUMBER_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_EMERGENCY_1_PHONENUMBER_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 1:.
        /// </summary>
        internal static string TITLE_CONTACT_EMERGENCY_1_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_EMERGENCY_1_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Relationship to contact 2:.
        /// </summary>
        internal static string TITLE_CONTACT_EMERGENCY_2_FAMILYRELATIONSHIP_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_EMERGENCY_2_FAMILYRELATIONSHIP_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact&apos;s 2 phone number:.
        /// </summary>
        internal static string TITLE_CONTACT_EMERGENCY_2_PHONENUMBER_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_EMERGENCY_2_PHONENUMBER_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 2:.
        /// </summary>
        internal static string TITLE_CONTACT_EMERGENCY_2_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_EMERGENCY_2_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me an emergency contact.
        /// </summary>
        internal static string TITLE_CONTACT_EMERGENCY_CASES {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_EMERGENCY_CASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you wish, you can inform me of a second emergency contact (optional).
        /// </summary>
        internal static string TITLE_CONTACT_EMERGENCY_CASES_OPTIONAL {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_EMERGENCY_CASES_OPTIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string TITLE_CONTACTS {
            get {
                return ResourceManager.GetString("TITLE_CONTACTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} countries available..
        /// </summary>
        internal static string TITLE_COUNTRY_AVALIABLE {
            get {
                return ResourceManager.GetString("TITLE_COUNTRY_AVALIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string TITLE_COUNTRY_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_COUNTRY_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a home.
        /// </summary>
        internal static string TITLE_CREATE_HOME {
            get {
                return ResourceManager.GetString("TITLE_CREATE_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create schedule now.
        /// </summary>
        internal static string TITLE_CREATE_SCHEDULE_NOW {
            get {
                return ResourceManager.GetString("TITLE_CREATE_SCHEDULE_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password:.
        /// </summary>
        internal static string TITLE_CURRENT_PASSWORD_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CURRENT_PASSWORD_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string TITLE_DAY {
            get {
                return ResourceManager.GetString("TITLE_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string TITLE_DAYS {
            get {
                return ResourceManager.GetString("TITLE_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline for rent payment:.
        /// </summary>
        internal static string TITLE_DEADLINE_PAYMENT_RENT_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_DEADLINE_PAYMENT_RENT_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined!.
        /// </summary>
        internal static string TITLE_DECLINED {
            get {
                return ResourceManager.GetString("TITLE_DECLINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string TITLE_DELETE {
            get {
                return ResourceManager.GetString("TITLE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        internal static string TITLE_DELETE_ACCOUNT {
            get {
                return ResourceManager.GetString("TITLE_DELETE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete home.
        /// </summary>
        internal static string TITLE_DELETE_HOME {
            get {
                return ResourceManager.GetString("TITLE_DELETE_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string TITLE_DETAILS {
            get {
                return ResourceManager.GetString("TITLE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dining room.
        /// </summary>
        internal static string TITLE_DINING_ROOM {
            get {
                return ResourceManager.GetString("TITLE_DINING_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date:.
        /// </summary>
        internal static string TITLE_DUEDATE_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_DUEDATE_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string TITLE_EDIT {
            get {
                return ResourceManager.GetString("TITLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the email to recover the password?.
        /// </summary>
        internal static string TITLE_EMAIL_RECOVER_PASSAWORD {
            get {
                return ResourceManager.GetString("TITLE_EMAIL_RECOVER_PASSAWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        internal static string TITLE_EMAIL_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_EMAIL_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency contacts:.
        /// </summary>
        internal static string TITLE_EMERGENCY_CONTACTS_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_EMERGENCY_CONTACTS_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry date:.
        /// </summary>
        internal static string TITLE_ENTRY_DATE_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_ENTRY_DATE_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Relationship:.
        /// </summary>
        internal static string TITLE_FAMILYRELATIONSHIP_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_FAMILYRELATIONSHIP_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finances.
        /// </summary>
        internal static string TITLE_FINANCES {
            get {
                return ResourceManager.GetString("TITLE_FINANCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For security reasons, enter your password and the code we sent in your email below to finish the process..
        /// </summary>
        internal static string TITLE_FOR_SECURITY_REASONS_PASSWORD_AND_CODE_EMAIL {
            get {
                return ResourceManager.GetString("TITLE_FOR_SECURITY_REASONS_PASSWORD_AND_CODE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string TITLE_FORGOT_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_FORGOT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frid.
        /// </summary>
        internal static string TITLE_FRIDAY_ABBREVIATED {
            get {
                return ResourceManager.GetString("TITLE_FRIDAY_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} friends available..
        /// </summary>
        internal static string TITLE_FRIENDS_AVALIABLE {
            get {
                return ResourceManager.GetString("TITLE_FRIENDS_AVALIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend&apos;s tasks.
        /// </summary>
        internal static string TITLE_FRIENDS_TASKS {
            get {
                return ResourceManager.GetString("TITLE_FRIENDS_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating code ....
        /// </summary>
        internal static string TITLE_GENERATING_CODE {
            get {
                return ResourceManager.GetString("TITLE_GENERATING_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a nice day,.
        /// </summary>
        internal static string TITLE_HAVE_NICE_DAY {
            get {
                return ResourceManager.GetString("TITLE_HAVE_NICE_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home, sweet home.
        /// </summary>
        internal static string TITLE_HOME_SWEET_HOME {
            get {
                return ResourceManager.GetString("TITLE_HOME_SWEET_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housework.
        /// </summary>
        internal static string TITLE_HOUSEWORK {
            get {
                return ResourceManager.GetString("TITLE_HOUSEWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon sources and Illustrations used:.
        /// </summary>
        internal static string TITLE_ICON_SOURCE_ILUSTRATIONS_USED_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_ICON_SOURCE_ILUSTRATIONS_USED_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information is saved with encryption and we will not share it with anyone. You can edit or delete at any time..
        /// </summary>
        internal static string TITLE_INFORMATION_NOT_SHARED_AND_SAVED_ENCRYPTION {
            get {
                return ResourceManager.GetString("TITLE_INFORMATION_NOT_SHARED_AND_SAVED_ENCRYPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligent Habitacion is your tool and a new way to organize your home..
        /// </summary>
        internal static string TITLE_INTELLIGENT_HABITACION_TOOL_NEW_WAY_ORGANIZE_HOME {
            get {
                return ResourceManager.GetString("TITLE_INTELLIGENT_HABITACION_TOOL_NEW_WAY_ORGANIZE_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s so sad see you go :((.
        /// </summary>
        internal static string TITLE_ITISSAD_SEEYOUGO {
            get {
                return ResourceManager.GetString("TITLE_ITISSAD_SEEYOUGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s great to see you here 😍.
        /// </summary>
        internal static string TITLE_ITS_GREAT_SEE_YOU_HERE {
            get {
                return ResourceManager.GetString("TITLE_ITS_GREAT_SEE_YOU_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join a home.
        /// </summary>
        internal static string TITLE_JOIN_HOME {
            get {
                return ResourceManager.GetString("TITLE_JOIN_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined on {0}.
        /// </summary>
        internal static string TITLE_JOINED_ON {
            get {
                return ResourceManager.GetString("TITLE_JOINED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogram(s).
        /// </summary>
        internal static string TITLE_KILOGRAM {
            get {
                return ResourceManager.GetString("TITLE_KILOGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen.
        /// </summary>
        internal static string TITLE_KITCHEN {
            get {
                return ResourceManager.GetString("TITLE_KITCHEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last record: {0}.
        /// </summary>
        internal static string TITLE_LAST_RECORD {
            get {
                return ResourceManager.GetString("TITLE_LAST_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laundry.
        /// </summary>
        internal static string TITLE_LAUNDRY {
            get {
                return ResourceManager.GetString("TITLE_LAUNDRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want you can leave a comment.
        /// </summary>
        internal static string TITLE_LEAVE_COMMENT_IF_YOU_WANTE {
            get {
                return ResourceManager.GetString("TITLE_LEAVE_COMMENT_IF_YOU_WANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living room.
        /// </summary>
        internal static string TITLE_LIVING_ROOM {
            get {
                return ResourceManager.GetString("TITLE_LIVING_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string TITLE_LOGIN {
            get {
                return ResourceManager.GetString("TITLE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to continue.
        /// </summary>
        internal static string TITLE_LOGIN_TO_CONTINUE {
            get {
                return ResourceManager.GetString("TITLE_LOGIN_TO_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with fingerprint access.
        /// </summary>
        internal static string TITLE_LOGIN_WITH_FINGERPRINT_ACCESS {
            get {
                return ResourceManager.GetString("TITLE_LOGIN_WITH_FINGERPRINT_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the first schedule.
        /// </summary>
        internal static string TITLE_MANAGE_SCHEDULE {
            get {
                return ResourceManager.GetString("TITLE_MANAGE_SCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer:.
        /// </summary>
        internal static string TITLE_MANUFACTURER_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_MANUFACTURER_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        internal static string TITLE_MONDAY_ABBREVIATED {
            get {
                return ResourceManager.GetString("TITLE_MONDAY_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        internal static string TITLE_MONTH {
            get {
                return ResourceManager.GetString("TITLE_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly rent:.
        /// </summary>
        internal static string TITLE_MONTHLYRENT_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_MONTHLYRENT_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string TITLE_MONTHS {
            get {
                return ResourceManager.GetString("TITLE_MONTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My data.
        /// </summary>
        internal static string TITLE_MY_DATA {
            get {
                return ResourceManager.GetString("TITLE_MY_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My foods.
        /// </summary>
        internal static string TITLE_MY_FOODS {
            get {
                return ResourceManager.GetString("TITLE_MY_FOODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My friends.
        /// </summary>
        internal static string TITLE_MY_FRIENDS {
            get {
                return ResourceManager.GetString("TITLE_MY_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My informations.
        /// </summary>
        internal static string TITLE_MY_INFORMATIONS {
            get {
                return ResourceManager.GetString("TITLE_MY_INFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tasks.
        /// </summary>
        internal static string TITLE_MY_TASKS {
            get {
                return ResourceManager.GetString("TITLE_MY_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string TITLE_NAME_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_NAME_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Neighborhood.
        /// </summary>
        internal static string TITLE_NEIGHBORHOOD {
            get {
                return ResourceManager.GetString("TITLE_NEIGHBORHOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighborhood:.
        /// </summary>
        internal static string TITLE_NEIGHBORHOOD_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_NEIGHBORHOOD_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New item.
        /// </summary>
        internal static string TITLE_NEW_ITEM {
            get {
                return ResourceManager.GetString("TITLE_NEW_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password:.
        /// </summary>
        internal static string TITLE_NEW_PASSWORD_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_NEW_PASSWORD_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string TITLE_NEXT {
            get {
                return ResourceManager.GetString("TITLE_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comments.
        /// </summary>
        internal static string TITLE_NO_COMMENTS {
            get {
                return ResourceManager.GetString("TITLE_NO_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results matched your filter..
        /// </summary>
        internal static string TITLE_NO_RESULTS_MATCHED_FILTER {
            get {
                return ResourceManager.GetString("TITLE_NO_RESULTS_MATCHED_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tasks.
        /// </summary>
        internal static string TITLE_NO_TASKS {
            get {
                return ResourceManager.GetString("TITLE_NO_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No task for this month..
        /// </summary>
        internal static string TITLE_NO_TASKS_FOR_THIS_MONTH {
            get {
                return ResourceManager.GetString("TITLE_NO_TASKS_FOR_THIS_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not.
        /// </summary>
        internal static string TITLE_NOT {
            get {
                return ResourceManager.GetString("TITLE_NOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify that an order has arrived.
        /// </summary>
        internal static string TITLE_NOTIFY_ORDER_ARRIVED {
            get {
                return ResourceManager.GetString("TITLE_NOTIFY_ORDER_ARRIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now your phone number.
        /// </summary>
        internal static string TITLE_NOW_YOUR_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("TITLE_NOW_YOUR_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string TITLE_OFFICE {
            get {
                return ResourceManager.GetString("TITLE_OFFICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package(s).
        /// </summary>
        internal static string TITLE_PACKAGE {
            get {
                return ResourceManager.GetString("TITLE_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirmation:.
        /// </summary>
        internal static string TITLE_PASSWORD_CONFIRMATION_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_PASSWORD_CONFIRMATION_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string TITLE_PASSWORD_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_PASSWORD_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number 1:.
        /// </summary>
        internal static string TITLE_PHONENUMBER_1_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_PHONENUMBER_1_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number 2:.
        /// </summary>
        internal static string TITLE_PHONENUMBER_2_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_PHONENUMBER_2_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonenumber:.
        /// </summary>
        internal static string TITLE_PHONENUMBER_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_PHONENUMBER_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonenumbers.
        /// </summary>
        internal static string TITLE_PHONENUMBERS {
            get {
                return ResourceManager.GetString("TITLE_PHONENUMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) Leave your feedback ....
        /// </summary>
        internal static string TITLE_PLACEHOLDER_LEAVE_YOUR_FEEDBACK {
            get {
                return ResourceManager.GetString("TITLE_PLACEHOLDER_LEAVE_YOUR_FEEDBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For security reasons, please log in again..
        /// </summary>
        internal static string TITLE_PLEASE_LOGIN_AGAIN {
            get {
                return ResourceManager.GetString("TITLE_PLEASE_LOGIN_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product:.
        /// </summary>
        internal static string TITLE_PRODUCT_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_PRODUCT_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} products avaliables.
        /// </summary>
        internal static string TITLE_PRODUCTS_AVALIABLES {
            get {
                return ResourceManager.GetString("TITLE_PRODUCTS_AVALIABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        internal static string TITLE_QUANTITY_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_QUANTITY_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign random tasks.
        /// </summary>
        internal static string TITLE_RANDOM_ASSIGNMENT {
            get {
                return ResourceManager.GetString("TITLE_RANDOM_ASSIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string TITLE_RATE {
            get {
                return ResourceManager.GetString("TITLE_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string TITLE_RATING {
            get {
                return ResourceManager.GetString("TITLE_RATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended:.
        /// </summary>
        internal static string TITLE_RECOMMENDED_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_RECOMMENDED_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string TITLE_REGISTER {
            get {
                return ResourceManager.GetString("TITLE_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi-fi network information (Optional).
        /// </summary>
        internal static string TITLE_REGISTER_NETWORK_INFORMATION {
            get {
                return ResourceManager.GetString("TITLE_REGISTER_NETWORK_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string TITLE_REMOVE {
            get {
                return ResourceManager.GetString("TITLE_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string TITLE_RETURN {
            get {
                return ResourceManager.GetString("TITLE_RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cleaned :).
        /// </summary>
        internal static string TITLE_ROOM_CLEANED {
            get {
                return ResourceManager.GetString("TITLE_ROOM_CLEANED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room:.
        /// </summary>
        internal static string TITLE_ROOM_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_ROOM_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        internal static string TITLE_ROOMS {
            get {
                return ResourceManager.GetString("TITLE_ROOMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms in the house.
        /// </summary>
        internal static string TITLE_ROOMS_IN_THE_HOUSE {
            get {
                return ResourceManager.GetString("TITLE_ROOMS_IN_THE_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        internal static string TITLE_SATURDAY_ABBREVIATED {
            get {
                return ResourceManager.GetString("TITLE_SATURDAY_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string TITLE_SAVE {
            get {
                return ResourceManager.GetString("TITLE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and new.
        /// </summary>
        internal static string TITLE_SAVE_AND_NEW {
            get {
                return ResourceManager.GetString("TITLE_SAVE_AND_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule setting.
        /// </summary>
        internal static string TITLE_SCHEDULE_SETTING {
            get {
                return ResourceManager.GetString("TITLE_SCHEDULE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name.
        /// </summary>
        internal static string TITLE_SEARCH_BY_NAME {
            get {
                return ResourceManager.GetString("TITLE_SEARCH_BY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more details.
        /// </summary>
        internal static string TITLE_SEE_MORE_DETAILS {
            get {
                return ResourceManager.GetString("TITLE_SEE_MORE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the rooms below to be cleaned..
        /// </summary>
        internal static string TITLE_SELECT_ROOMS_BELOW_TO_BE_CLEANED {
            get {
                return ResourceManager.GetString("TITLE_SELECT_ROOMS_BELOW_TO_BE_CLEANED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending data ....
        /// </summary>
        internal static string TITLE_SENDING_DATA {
            get {
                return ResourceManager.GetString("TITLE_SENDING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending QRCode ....
        /// </summary>
        internal static string TITLE_SENDING_QRCODE {
            get {
                return ResourceManager.GetString("TITLE_SENDING_QRCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as administrator.
        /// </summary>
        internal static string TITLE_SET_AS_ADMINISTRATOR {
            get {
                return ResourceManager.GetString("TITLE_SET_AS_ADMINISTRATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        internal static string TITLE_SHOPPING {
            get {
                return ResourceManager.GetString("TITLE_SHOPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        internal static string TITLE_STATE_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_STATE_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success :).
        /// </summary>
        internal static string TITLE_SUCCESS {
            get {
                return ResourceManager.GetString("TITLE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        internal static string TITLE_SUNDAY_ABBREVIATED {
            get {
                return ResourceManager.GetString("TITLE_SUNDAY_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks:.
        /// </summary>
        internal static string TITLE_TASKS_TWO_POINTS {
            get {
                return ResourceManager.GetString("TITLE_TASKS_TWO_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City is:.
        /// </summary>
        internal static string TITLE_THE_CITY_IS {
            get {
                return ResourceManager.GetString("TITLE_THE_CITY_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will expire in:.
        /// </summary>
        internal static string TITLE_THIS_OPERATION_WILL_EXPIRE {
            get {
                return ResourceManager.GetString("TITLE_THIS_OPERATION_WILL_EXPIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        internal static string TITLE_THURSDAY_ABBREVIATED {
            get {
                return ResourceManager.GetString("TITLE_THURSDAY_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time has expired. Please try again..
        /// </summary>
        internal static string TITLE_TIME_EXPIRED_TRY_AGAIN {
            get {
                return ResourceManager.GetString("TITLE_TIME_EXPIRED_TRY_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To finish. Your password.
        /// </summary>
        internal static string TITLE_TO_FINISH_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_TO_FINISH_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To begin :) Tell me what is your e-mail.
        /// </summary>
        internal static string TITLE_TOBEGIN_TELL_EMAIL {
            get {
                return ResourceManager.GetString("TITLE_TOBEGIN_TELL_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}.
        /// </summary>
        internal static string TITLE_TOTAL {
            get {
                return ResourceManager.GetString("TITLE_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch the screen to focus..
        /// </summary>
        internal static string TITLE_TOUCH_SCREEN_TO_FOCUS {
            get {
                return ResourceManager.GetString("TITLE_TOUCH_SCREEN_TO_FOCUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        internal static string TITLE_TUESDAY_ABBREVIATED {
            get {
                return ResourceManager.GetString("TITLE_TUESDAY_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string TITLE_TYPE_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_TYPE_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity(s).
        /// </summary>
        internal static string TITLE_UNITY {
            get {
                return ResourceManager.GetString("TITLE_UNITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating tasks.
        /// </summary>
        internal static string TITLE_UPDATING_TASKS {
            get {
                return ResourceManager.GetString("TITLE_UPDATING_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can login using your fingerprint. Click here :).
        /// </summary>
        internal static string TITLE_USE_YOUR_FIGERPRINT_TO_LOGIN {
            get {
                return ResourceManager.GetString("TITLE_USE_YOUR_FIGERPRINT_TO_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating operation ....
        /// </summary>
        internal static string TITLE_VALIDATING_OPERATION {
            get {
                return ResourceManager.GetString("TITLE_VALIDATING_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string TITLE_VERSION {
            get {
                return ResourceManager.GetString("TITLE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Administrator ....
        /// </summary>
        internal static string TITLE_WAITING_FOR_ADMINISTRATOR {
            get {
                return ResourceManager.GetString("TITLE_WAITING_FOR_ADMINISTRATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warming up engines ....
        /// </summary>
        internal static string TITLE_WARMING_UP_ENGINES {
            get {
                return ResourceManager.GetString("TITLE_WARMING_UP_ENGINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        internal static string TITLE_WEDNESDAY_ABBREVIATED {
            get {
                return ResourceManager.GetString("TITLE_WEDNESDAY_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome :).
        /// </summary>
        internal static string TITLE_WELCOME {
            get {
                return ResourceManager.GetString("TITLE_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What did you think of the cleaning?.
        /// </summary>
        internal static string TITLE_WHAT_THINK_CLEANING {
            get {
                return ResourceManager.GetString("TITLE_WHAT_THINK_CLEANING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why do I need to fill this information?.
        /// </summary>
        internal static string TITLE_WHY_NEED_FILL_THIS_INFORMATION {
            get {
                return ResourceManager.GetString("TITLE_WHY_NEED_FILL_THIS_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        internal static string TITLE_YEAR {
            get {
                return ResourceManager.GetString("TITLE_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        internal static string TITLE_YEARS {
            get {
                return ResourceManager.GetString("TITLE_YEARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I&apos;m sure.
        /// </summary>
        internal static string TITLE_YES_IAMSURE {
            get {
                return ResourceManager.GetString("TITLE_YES_IAMSURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your evaluation.
        /// </summary>
        internal static string TITLE_YOUR_EVALUATION {
            get {
                return ResourceManager.GetString("TITLE_YOUR_EVALUATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name ;).
        /// </summary>
        internal static string TITLE_YOUR_NAME {
            get {
                return ResourceManager.GetString("TITLE_YOUR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCode:.
        /// </summary>
        internal static string TITLE_ZIPCODE_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_ZIPCODE_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        internal static string TITULO_LOGGOUT {
            get {
                return ResourceManager.GetString("TITULO_LOGGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom.
        /// </summary>
        internal static string UNITED_KINGDOM {
            get {
                return ResourceManager.GetString("UNITED_KINGDOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States.
        /// </summary>
        internal static string UNITED_STATES {
            get {
                return ResourceManager.GetString("UNITED_STATES", resourceCulture);
            }
        }
    }
}
