//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentHabitacion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntelligentHabitacion.ResourceText", typeof(ResourceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because live with friends.
        /// </summary>
        public static string BECAUSE_LIVE_WITH_FRIENDS {
            get {
                return ResourceManager.GetString("BECAUSE_LIVE_WITH_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to create a home and be the administrator..
        /// </summary>
        public static string DESCRIPTION_CREATE_HOME {
            get {
                return ResourceManager.GetString("DESCRIPTION_CREATE_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to be part of a home already created..
        /// </summary>
        public static string DESCRIPTION_JOIN_HOME {
            get {
                return ResourceManager.GetString("DESCRIPTION_JOIN_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to see and/or edit your registry information..
        /// </summary>
        public static string DESCRIPTION_MY_INFORMATIONS {
            get {
                return ResourceManager.GetString("DESCRIPTION_MY_INFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be fun and organized.
        /// </summary>
        public static string MUST_BE_FUN_AND_ORGANIZED {
            get {
                return ResourceManager.GetString("MUST_BE_FUN_AND_ORGANIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rua Mountain Drive.
        /// </summary>
        public static string PLACEHOLDER_ADDRESS {
            get {
                return ResourceManager.GetString("PLACEHOLDER_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7º Floor.
        /// </summary>
        public static string PLACEHOLDER_ADDRESSCOMPLEMENT {
            get {
                return ResourceManager.GetString("PLACEHOLDER_ADDRESSCOMPLEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1007.
        /// </summary>
        public static string PLACEHOLDER_ADDRESSNUMBER {
            get {
                return ResourceManager.GetString("PLACEHOLDER_ADDRESSNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gotham City.
        /// </summary>
        public static string PLACEHOLDER_CITY {
            get {
                return ResourceManager.GetString("PLACEHOLDER_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code received in email.
        /// </summary>
        public static string PLACEHOLDER_CODE_RECEIVED {
            get {
                return ResourceManager.GetString("PLACEHOLDER_CODE_RECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree of kinship.
        /// </summary>
        public static string PLACEHOLDER_DEGREE_KINSHIP {
            get {
                return ResourceManager.GetString("PLACEHOLDER_DEGREE_KINSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bruce@waynetech.com.
        /// </summary>
        public static string PLACEHOLDER_EMAIL {
            get {
                return ResourceManager.GetString("PLACEHOLDER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother.
        /// </summary>
        public static string PLACEHOLDER_EMERGENCYCONTACT1_FAMILYRELANTIONSHIP {
            get {
                return ResourceManager.GetString("PLACEHOLDER_EMERGENCYCONTACT1_FAMILYRELANTIONSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martha Wayne.
        /// </summary>
        public static string PLACEHOLDER_EMERGENCYCONTACT1_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_EMERGENCYCONTACT1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        public static string PLACEHOLDER_EMERGENCYCONTACT2_FAMILYRELANTIONSHIP {
            get {
                return ResourceManager.GetString("PLACEHOLDER_EMERGENCYCONTACT2_FAMILYRELANTIONSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thomas Wayne.
        /// </summary>
        public static string PLACEHOLDER_EMERGENCYCONTACT2_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_EMERGENCYCONTACT2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruce Wayne.
        /// </summary>
        public static string PLACEHOLDER_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palisades.
        /// </summary>
        public static string PLACEHOLDER_NEIGHBORHOOD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_NEIGHBORHOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network&apos;s name ....
        /// </summary>
        public static string PLACEHOLDER_NETWORK_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_NETWORK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string PLACEHOLDER_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PLACEHOLDER_PASSWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation password.
        /// </summary>
        public static string PLACEHOLDER_PASSWORD_CONFIRMATION {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PASSWORD_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (31) 9 0000-0000 .
        /// </summary>
        public static string PLACEHOLDER_PHONENUMBER {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PHONENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.275-972.
        /// </summary>
        public static string PLACEHOLDER_ZIPCODE {
            get {
                return ResourceManager.GetString("PLACEHOLDER_ZIPCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the App.
        /// </summary>
        public static string TITILE_ABOUT_APP {
            get {
                return ResourceManager.GetString("TITILE_ABOUT_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now the address.
        /// </summary>
        public static string TITLE_ADDRESS {
            get {
                return ResourceManager.GetString("TITLE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any complement?.
        /// </summary>
        public static string TITLE_ADDRESSCOMPLEMENT {
            get {
                return ResourceManager.GetString("TITLE_ADDRESSCOMPLEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the number?.
        /// </summary>
        public static string TITLE_ADDRESSNUMBER {
            get {
                return ResourceManager.GetString("TITLE_ADDRESSNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string TITLE_CHANGE {
            get {
                return ResourceManager.GetString("TITLE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code received:.
        /// </summary>
        public static string TITLE_CODE_RECEIVED_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CODE_RECEIVED_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conclude.
        /// </summary>
        public static string TITLE_CONCLUDE {
            get {
                return ResourceManager.GetString("TITLE_CONCLUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me an emergency contact.
        /// </summary>
        public static string TITLE_CONTACT_EMERGENCY_CASES {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_EMERGENCY_CASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you wish, you can inform me of a second emergency contact (optional).
        /// </summary>
        public static string TITLE_CONTACT_EMERGENCY_CASES_OPTIONAL {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_EMERGENCY_CASES_OPTIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a home.
        /// </summary>
        public static string TITLE_CREATE_HOME {
            get {
                return ResourceManager.GetString("TITLE_CREATE_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the email to recover the password?.
        /// </summary>
        public static string TITLE_EMAIL_RECOVER_PASSAWORD {
            get {
                return ResourceManager.GetString("TITLE_EMAIL_RECOVER_PASSAWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        public static string TITLE_EMAIL_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_EMAIL_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string TITLE_FORGOT_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_FORGOT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join a home.
        /// </summary>
        public static string TITLE_JOIN_HOME {
            get {
                return ResourceManager.GetString("TITLE_JOIN_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to continue.
        /// </summary>
        public static string TITLE_LOGIN_TO_CONTINUE {
            get {
                return ResourceManager.GetString("TITLE_LOGIN_TO_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My informations.
        /// </summary>
        public static string TITLE_MY_INFORMATIONS {
            get {
                return ResourceManager.GetString("TITLE_MY_INFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Neighborhood.
        /// </summary>
        public static string TITLE_NEIGHBORHOOD {
            get {
                return ResourceManager.GetString("TITLE_NEIGHBORHOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password:.
        /// </summary>
        public static string TITLE_NEW_PASSWORD_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_NEW_PASSWORD_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string TITLE_NEXT {
            get {
                return ResourceManager.GetString("TITLE_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now your phone number.
        /// </summary>
        public static string TITLE_NOW_YOUR_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("TITLE_NOW_YOUR_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirmation:.
        /// </summary>
        public static string TITLE_PASSWORD_CONFIRMATION_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_PASSWORD_CONFIRMATION_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string TITLE_PASSWORD_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_PASSWORD_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string TITLE_REGISTER {
            get {
                return ResourceManager.GetString("TITLE_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To finish :) Wi-fi network information.
        /// </summary>
        public static string TITLE_REGISTER_NETWORK_INFORMATION {
            get {
                return ResourceManager.GetString("TITLE_REGISTER_NETWORK_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string TITLE_RETURN {
            get {
                return ResourceManager.GetString("TITLE_RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me the Zip Code :).
        /// </summary>
        public static string TITLE_TELLME_ZIPCODE {
            get {
                return ResourceManager.GetString("TITLE_TELLME_ZIPCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City is:.
        /// </summary>
        public static string TITLE_THE_CITY_IS {
            get {
                return ResourceManager.GetString("TITLE_THE_CITY_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To finish. Your password.
        /// </summary>
        public static string TITLE_TO_FINISH_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_TO_FINISH_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To begin :) Tell me what is your name.
        /// </summary>
        public static string TITLE_TOBEGIN_TELL_NAME {
            get {
                return ResourceManager.GetString("TITLE_TOBEGIN_TELL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string TITLE_VERSION {
            get {
                return ResourceManager.GetString("TITLE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome :).
        /// </summary>
        public static string TITLE_WELCOME {
            get {
                return ResourceManager.GetString("TITLE_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-mail :).
        /// </summary>
        public static string TITLE_YOUR_EMAIL {
            get {
                return ResourceManager.GetString("TITLE_YOUR_EMAIL", resourceCulture);
            }
        }
    }
}
