//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentHabitacion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntelligentHabitacion.ResourceText", typeof(ResourceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because live with friends.
        /// </summary>
        public static string BECAUSE_LIVE_WITH_FRIENDS {
            get {
                return ResourceManager.GetString("BECAUSE_LIVE_WITH_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be fun and organized.
        /// </summary>
        public static string MUST_BE_FUN_AND_ORGANIZED {
            get {
                return ResourceManager.GetString("MUST_BE_FUN_AND_ORGANIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the email to recover the password?.
        /// </summary>
        public static string PHRASE_EMAIL_RECOVER_PASSAWORD {
            get {
                return ResourceManager.GetString("PHRASE_EMAIL_RECOVER_PASSAWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string TITLE_CHANGE {
            get {
                return ResourceManager.GetString("TITLE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code received.
        /// </summary>
        public static string TITLE_CODE_RECEIVED {
            get {
                return ResourceManager.GetString("TITLE_CODE_RECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code received:.
        /// </summary>
        public static string TITLE_CODE_RECEIVED_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_CODE_RECEIVED_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string TITLE_EMAIL {
            get {
                return ResourceManager.GetString("TITLE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        public static string TITLE_EMAIL_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_EMAIL_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string TITLE_FORGOT_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_FORGOT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to continue.
        /// </summary>
        public static string TITLE_LOGIN_TO_CONTINUE {
            get {
                return ResourceManager.GetString("TITLE_LOGIN_TO_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string TITLE_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password:.
        /// </summary>
        public static string TITLE_NEW_PASSWORD_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_NEW_PASSWORD_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string TITLE_NEXT {
            get {
                return ResourceManager.GetString("TITLE_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string TITLE_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirmation.
        /// </summary>
        public static string TITLE_PASSWORD_CONFIRMATION {
            get {
                return ResourceManager.GetString("TITLE_PASSWORD_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirmation:.
        /// </summary>
        public static string TITLE_PASSWORD_CONFIRMATION_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_PASSWORD_CONFIRMATION_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string TITLE_PASSWORD_TWOPOINTS {
            get {
                return ResourceManager.GetString("TITLE_PASSWORD_TWOPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string TITLE_REGISTER {
            get {
                return ResourceManager.GetString("TITLE_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type here ....
        /// </summary>
        public static string TITLE_TYPE_HERE {
            get {
                return ResourceManager.GetString("TITLE_TYPE_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome :).
        /// </summary>
        public static string TITLE_WELCOME {
            get {
                return ResourceManager.GetString("TITLE_WELCOME", resourceCulture);
            }
        }
    }
}
