//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homuai.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceTextException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTextException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homuai.Exception.ResourceTextException", typeof(ResourceTextException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duedate must be grater than today..
        /// </summary>
        public static string DUEDATE_MUST_BE_GRATER_THAN_TODAY {
            get {
                return ResourceManager.GetString("DUEDATE_MUST_BE_GRATER_THAN_TODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address has already been registered..
        /// </summary>
        public static string EMAIL_ALREADYBEENREGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADYBEENREGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail must be entered..
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The E-mail is invalid..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency contacts cannot have the same phone number..
        /// </summary>
        public static string EMERGENCY_CONTACT_SAME_PHONENUMBER {
            get {
                return ResourceManager.GetString("EMERGENCY_CONTACT_SAME_PHONENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An emergency contact must be informed..
        /// </summary>
        public static string EMERGENCYCONTACT_EMPTY {
            get {
                return ResourceManager.GetString("EMERGENCYCONTACT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can inform a maximum of 2 emergency contacts..
        /// </summary>
        public static string EMERGENCYCONTACT_MAX_TWO {
            get {
                return ResourceManager.GetString("EMERGENCYCONTACT_MAX_TWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters..
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be entered..
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password must be entered..
        /// </summary>
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One phonenumber must be entered for the Emergency contact..
        /// </summary>
        public static string PHONENUMBER_EMERGENCY_CONTACT_EMPTY {
            get {
                return ResourceManager.GetString("PHONENUMBER_EMERGENCY_CONTACT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One phone number must be entered..
        /// </summary>
        public static string PHONENUMBER_EMPTY {
            get {
                return ResourceManager.GetString("PHONENUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can enter a maximum of 2 phonenumbers..
        /// </summary>
        public static string PHONENUMBER_MAX_TWO {
            get {
                return ResourceManager.GetString("PHONENUMBER_MAX_TWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone numbers are the same..
        /// </summary>
        public static string PHONENUMBERS_ARE_SAME {
            get {
                return ResourceManager.GetString("PHONENUMBERS_ARE_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product name must be entered..
        /// </summary>
        public static string PRODUCT_NAME_EMPTY {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The push notification id is invalid..
        /// </summary>
        public static string PUSHNOTIFICATION_INVALID {
            get {
                return ResourceManager.GetString("PUSHNOTIFICATION_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity of products is invalid..
        /// </summary>
        public static string QUANTITY_PRODUCTS_INVALID {
            get {
                return ResourceManager.GetString("QUANTITY_PRODUCTS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Emergency contact&apos;s name must be entered..
        /// </summary>
        public static string THE_NAME_EMERGENCY_CONTACT_INVALID {
            get {
                return ResourceManager.GetString("THE_NAME_EMERGENCY_CONTACT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Relationship with the Emergency contact must be entered..
        /// </summary>
        public static string THE_RELATIONSHIP_EMERGENCY_CONTACT_INVALID {
            get {
                return ResourceManager.GetString("THE_RELATIONSHIP_EMERGENCY_CONTACT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product&apos;s type is invalid..
        /// </summary>
        public static string TYPE_PRODUCTS_INVALID {
            get {
                return ResourceManager.GetString("TYPE_PRODUCTS_INVALID", resourceCulture);
            }
        }
    }
}
