using System.Collections.Generic;
using System.Linq;

namespace IntelligentHabitacion.Useful
{
    public static class Country
    {
        private static List<CountryModel> _countries;

        public static List<CountryModel> Countries
        {
            get
            {
                if (_countries == null)
                    FillContryList();

                return _countries;
            }
        }

        private static void FillContryList()
        {
            _countries = new List<CountryModel>
            {
                new CountryModel{Id = CountryEnum.AFGHANISTAN, PhoneCode = "+93", Name = ResourceText.AFGHANISTAN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Afghanistan.svg/23px-Flag_of_Afghanistan.svg.png" },
                new CountryModel{Id = CountryEnum.SOUTH_AFRICA, PhoneCode = "+27", Name = ResourceText.SOUTH_AFRICA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/23px-Flag_of_South_Africa.svg.png" },
                new CountryModel{Id = CountryEnum.ALBANIA, PhoneCode = "+355", Name = ResourceText.ALBANIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/21px-Flag_of_Albania.svg.png" },
                new CountryModel{Id = CountryEnum.GERMANY, PhoneCode = "+49", Name = ResourceText.GERMANY, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/23px-Flag_of_Germany.svg.png" },
                new CountryModel{Id = CountryEnum.ANDORRA, PhoneCode = "+376", Name = ResourceText.ANDORRA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Andorra.svg/22px-Flag_of_Andorra.svg.png" },
                new CountryModel{Id = CountryEnum.ANGOLA, PhoneCode = "+244", Name = ResourceText.ANGOLA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/23px-Flag_of_Angola.svg.png" },
                new CountryModel{Id = CountryEnum.ANGUILLA, PhoneCode = "+1", Name = ResourceText.ANGUILLA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Anguilla.svg/23px-Flag_of_Anguilla.svg.png" },
                new CountryModel{Id = CountryEnum.ANTIGUA_AND_BARBUDA, PhoneCode = "+1", Name = ResourceText.ANTIGUA_AND_BARBUDA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/23px-Flag_of_Antigua_and_Barbuda.svg.png" },
                new CountryModel{Id = CountryEnum.NETHERLANDS_ANTILLES, PhoneCode = "+599", Name = ResourceText.NETHERLANDS_ANTILLES, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Flag_of_the_Netherlands_Antilles_%281986%E2%80%932010%29.svg/23px-Flag_of_the_Netherlands_Antilles_%281986%E2%80%932010%29.svg.png" },
                new CountryModel{Id = CountryEnum.SAUDI_ARABIA, PhoneCode = "+966", Name = ResourceText.SAUDI_ARABIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/23px-Flag_of_Saudi_Arabia.svg.png" },
                new CountryModel{Id = CountryEnum.ALGERIA, PhoneCode = "+213", Name = ResourceText.ALGERIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/23px-Flag_of_Algeria.svg.png" },
                new CountryModel{Id = CountryEnum.ARGENTINA, PhoneCode = "+54", Name = ResourceText.ARGENTINA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/23px-Flag_of_Argentina.svg.png" },
                new CountryModel{Id = CountryEnum.ARMENIA, PhoneCode = "+374", Name = ResourceText.ARMENIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/23px-Flag_of_Armenia.svg.png" },
                new CountryModel{Id = CountryEnum.ARUBA, PhoneCode = "+297", Name = ResourceText.ARUBA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Aruba.svg/23px-Flag_of_Aruba.svg.png" },
                new CountryModel{Id = CountryEnum.ASCENSION, PhoneCode = "+247", Name = ResourceText.ASCENSION, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Ascension_Island.svg/20px-Flag_of_Ascension_Island.svg.png" },
                new CountryModel{Id = CountryEnum.AUSTRALIA, PhoneCode = "+61", Name = ResourceText.AUSTRALIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/23px-Flag_of_Australia.svg.png" },
                new CountryModel{Id = CountryEnum.AUSTRIA, PhoneCode = "+43", Name = ResourceText.AUSTRIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/23px-Flag_of_Austria.svg.png" },
                new CountryModel{Id = CountryEnum.AZERBAIJAN, PhoneCode = "+994", Name = ResourceText.AZERBAIJAN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/23px-Flag_of_Azerbaijan.svg.png" },
                new CountryModel{Id = CountryEnum.BAHAMAS, PhoneCode = "+1", Name = ResourceText.BAHAMAS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Bahamas_Flag.svg/23px-Bahamas_Flag.svg.png" },
                new CountryModel{Id = CountryEnum.BANGLADESH, PhoneCode = "+880", Name = ResourceText.BANGLADESH, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/23px-Flag_of_Bangladesh.svg.png" },
                new CountryModel{Id = CountryEnum.BARBADOS, PhoneCode = "+1", Name = ResourceText.BARBADOS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/23px-Flag_of_Barbados.svg.png" },
                new CountryModel{Id = CountryEnum.BAHRAIN, PhoneCode = "+973", Name = ResourceText.BAHRAIN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/23px-Flag_of_Bahrain.svg.png" },
                new CountryModel{Id = CountryEnum.BELGIUM, PhoneCode = "+32", Name = ResourceText.BELGIUM, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/23px-Flag_of_Belgium_%28civil%29.svg.png" },
                new CountryModel{Id = CountryEnum.BELIZE, PhoneCode = "+501", Name = ResourceText.BELIZE, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Flag_of_Belize.svg/23px-Flag_of_Belize.svg.png" },
                new CountryModel{Id = CountryEnum.BENIN, PhoneCode = "+229", Name = ResourceText.BENIN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/23px-Flag_of_Benin.svg.png" },
                new CountryModel{Id = CountryEnum.BERMUDA, PhoneCode = "+1", Name = ResourceText.BERMUDA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bermuda.svg/23px-Flag_of_Bermuda.svg.png" },
                new CountryModel{Id = CountryEnum.BELARUS, PhoneCode = "+375", Name = ResourceText.BELARUS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/23px-Flag_of_Belarus.svg.png" },
                new CountryModel{Id = CountryEnum.BOLIVIA, PhoneCode = "+591", Name = ResourceText.BOLIVIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Bolivia.svg/22px-Flag_of_Bolivia.svg.png" },
                new CountryModel{Id = CountryEnum.BOSNIA_AND_HERZEGOVINA, PhoneCode = "+387", Name = ResourceText.BOSNIA_AND_HERZEGOVINA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/23px-Flag_of_Bosnia_and_Herzegovina.svg.png" },
                new CountryModel{Id = CountryEnum.BOTSWANA, PhoneCode = "+267", Name = ResourceText.BOTSWANA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/23px-Flag_of_Botswana.svg.png" },
                new CountryModel{Id = CountryEnum.BRAZIL, PhoneCode = "+55", Name = ResourceText.BRAZIL, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/22px-Flag_of_Brazil.svg.png" },
                new CountryModel{Id = CountryEnum.BRUNEI, PhoneCode = "+673", Name = ResourceText.BRUNEI, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/23px-Flag_of_Brunei.svg.png" },
                new CountryModel{Id = CountryEnum.BULGARIA, PhoneCode = "+359", Name = ResourceText.BULGARIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/23px-Flag_of_Bulgaria.svg.png" },
                new CountryModel{Id = CountryEnum.BURKINA_FASO, PhoneCode = "+226", Name = ResourceText.BURKINA_FASO, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/23px-Flag_of_Burkina_Faso.svg.png" },
                new CountryModel{Id = CountryEnum.BURUNDI, PhoneCode = "+257", Name = ResourceText.BURUNDI, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/23px-Flag_of_Burundi.svg.png" },
                new CountryModel{Id = CountryEnum.BHUTAN, PhoneCode = "+975", Name = ResourceText.BHUTAN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/23px-Flag_of_Bhutan.svg.png" },
                new CountryModel{Id = CountryEnum.CAPE_VERDE, PhoneCode = "+238", Name = ResourceText.CAPE_VERDE, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/23px-Flag_of_Cape_Verde.svg.png" },
                new CountryModel{Id = CountryEnum.CAMEROON, PhoneCode = "+237", Name = ResourceText.CAMEROON, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/23px-Flag_of_Cameroon.svg.png" },
                new CountryModel{Id = CountryEnum.CAMBODIA, PhoneCode = "+855", Name = ResourceText.CAMBODIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/23px-Flag_of_Cambodia.svg.png" },
                new CountryModel{Id = CountryEnum.CANADA, PhoneCode = "+1", Name = ResourceText.CANADA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/23px-Flag_of_Canada_%28Pantone%29.svg.png" },
                new CountryModel{Id = CountryEnum.KAZAKHSTAN, PhoneCode = "+7", Name = ResourceText.KAZAKHSTAN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/23px-Flag_of_Kazakhstan.svg.png" },
                new CountryModel{Id = CountryEnum.CHAD, PhoneCode = "+235", Name = ResourceText.CHAD, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Chad.svg/23px-Flag_of_Chad.svg.png" },
                new CountryModel{Id = CountryEnum.CHILE, PhoneCode = "+56", Name = ResourceText.CHILE, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/23px-Flag_of_Chile.svg.png" },
                new CountryModel{Id = CountryEnum.PEOPLE_REPUBLIC_OF_CHINA, PhoneCode = "+86", Name = ResourceText.PEOPLE_REPUBLIC_OF_CHINA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" },
                new CountryModel{Id = CountryEnum.CYPRUS, PhoneCode = "+357", Name = ResourceText.CYPRUS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/23px-Flag_of_Cyprus.svg.png" },
                new CountryModel{Id = CountryEnum.COLOMBIA, PhoneCode = "+57", Name = ResourceText.COLOMBIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/23px-Flag_of_Colombia.svg.png" },
                new CountryModel{Id = CountryEnum.COMOROS, PhoneCode = "+269", Name = ResourceText.COMOROS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/23px-Flag_of_the_Comoros.svg.png" },
                new CountryModel{Id = CountryEnum.REPUBLIC_OF_THE_CONGO, PhoneCode = "+242", Name = ResourceText.REPUBLIC_OF_THE_CONGO, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Republic_of_the_Congo.svg/23px-Flag_of_the_Republic_of_the_Congo.svg.png" },
                new CountryModel{Id = CountryEnum.DEMOCRATIC_REPUBLIC_OF_THE_CONGO, PhoneCode = "+243", Name = ResourceText.DEMOCRATIC_REPUBLIC_OF_THE_CONGO, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/20px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png" },
                new CountryModel{Id = CountryEnum.NORTH_KOREA, PhoneCode = "+850", Name = ResourceText.NORTH_KOREA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Flag_of_North_Korea.svg/23px-Flag_of_North_Korea.svg.png" },
                new CountryModel{Id = CountryEnum.SOUTH_KOREA, PhoneCode = "+82", Name = ResourceText.SOUTH_KOREA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/23px-Flag_of_South_Korea.svg.png" },
                new CountryModel{Id = CountryEnum.IVORY_COAST, PhoneCode = "+225", Name = ResourceText.IVORY_COAST, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg/23px-Flag_of_C%C3%B4te_d%27Ivoire.svg.png" },
                new CountryModel{Id = CountryEnum.COSTA_RICA, PhoneCode = "+506", Name = ResourceText.COSTA_RICA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Costa_Rica.svg/23px-Flag_of_Costa_Rica.svg.png" },
                new CountryModel{Id = CountryEnum.CROATIA, PhoneCode = "+385", Name = ResourceText.CROATIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/23px-Flag_of_Croatia.svg.png" },
                new CountryModel{Id = CountryEnum.CUBA, PhoneCode = "+53", Name = ResourceText.CUBA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/23px-Flag_of_Cuba.svg.png" },
                new CountryModel{Id = CountryEnum.DENMARK, PhoneCode = "+45", Name = ResourceText.DENMARK, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/20px-Flag_of_Denmark.svg.png" },
                new CountryModel{Id = CountryEnum.DJIBOUTI, PhoneCode = "+253", Name = ResourceText.DJIBOUTI, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Djibouti.svg/23px-Flag_of_Djibouti.svg.png" },
                new CountryModel{Id = CountryEnum.DOMINICA, PhoneCode = "+1", Name = ResourceText.DOMINICA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Flag_of_Dominica.svg/23px-Flag_of_Dominica.svg.png" },
                new CountryModel{Id = CountryEnum.EGYPT, PhoneCode = "+20", Name = ResourceText.EGYPT, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/23px-Flag_of_Egypt.svg.png" },
                new CountryModel{Id = CountryEnum.EL_SALVADOR, PhoneCode = "+503", Name = ResourceText.EL_SALVADOR, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/23px-Flag_of_El_Salvador.svg.png" },
                new CountryModel{Id = CountryEnum.UNITED_ARAB_EMIRATES, PhoneCode = "+971", Name = ResourceText.UNITED_ARAB_EMIRATES, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/23px-Flag_of_the_United_Arab_Emirates.svg.png" },
                new CountryModel{Id = CountryEnum.ECUADOR, PhoneCode = "+593", Name = ResourceText.ECUADOR, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/23px-Flag_of_Ecuador.svg.png" },
                new CountryModel{Id = CountryEnum.ERITREA, PhoneCode = "+291", Name = ResourceText.ERITREA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Eritrea.svg/23px-Flag_of_Eritrea.svg.png" },
                new CountryModel{Id = CountryEnum.SLOVAKIA, PhoneCode = "+421", Name = ResourceText.SLOVAKIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/23px-Flag_of_Slovakia.svg.png" },
                new CountryModel{Id = CountryEnum.SLOVENIA, PhoneCode = "+386", Name = ResourceText.SLOVENIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/23px-Flag_of_Slovenia.svg.png" },
                new CountryModel{Id = CountryEnum.SPAIN, PhoneCode = "+34", Name = ResourceText.SPAIN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/23px-Flag_of_Spain.svg.png" },
                new CountryModel{Id = CountryEnum.UNITED_STATES, PhoneCode = "+1", Name = ResourceText.UNITED_STATES, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" },
                new CountryModel{Id = CountryEnum.ESTONIA, PhoneCode = "+372", Name = ResourceText.ESTONIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/23px-Flag_of_Estonia.svg.png" },
                new CountryModel{Id = CountryEnum.ETHIOPIA, PhoneCode = "+251", Name = ResourceText.ETHIOPIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/23px-Flag_of_Ethiopia.svg.png" },
                new CountryModel{Id = CountryEnum.FIJI, PhoneCode = "+679", Name = ResourceText.FIJI, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Fiji.svg/23px-Flag_of_Fiji.svg.png" },
                new CountryModel{Id = CountryEnum.PHILIPPINES, PhoneCode = "+63", Name = ResourceText.PHILIPPINES, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/23px-Flag_of_the_Philippines.svg.png" },
                new CountryModel{Id = CountryEnum.FINLAND, PhoneCode = "+358", Name = ResourceText.FINLAND, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/23px-Flag_of_Finland.svg.png" },
                new CountryModel{Id = CountryEnum.FRANCE, PhoneCode = "+33", Name = ResourceText.FRANCE, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png" },
                new CountryModel{Id = CountryEnum.GABON, PhoneCode = "+241", Name = ResourceText.GABON, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Gabon.svg/20px-Flag_of_Gabon.svg.png" },
                new CountryModel{Id = CountryEnum.GAMBIA, PhoneCode = "+220", Name = ResourceText.GAMBIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_The_Gambia.svg/23px-Flag_of_The_Gambia.svg.png" },
                new CountryModel{Id = CountryEnum.GHANA, PhoneCode = "+233", Name = ResourceText.GHANA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/23px-Flag_of_Ghana.svg.png" },
                new CountryModel{Id = CountryEnum.GEORGIA, PhoneCode = "+995", Name = ResourceText.GEORGIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/23px-Flag_of_Georgia.svg.png" },
                new CountryModel{Id = CountryEnum.GIBRALTAR, PhoneCode = "+350", Name = ResourceText.GIBRALTAR, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Flag_of_Gibraltar.svg/23px-Flag_of_Gibraltar.svg.png" },
                new CountryModel{Id = CountryEnum.GRENADA, PhoneCode = "+1", Name = ResourceText.GRENADA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Grenada.svg/23px-Flag_of_Grenada.svg.png" },
                new CountryModel{Id = CountryEnum.GREECE, PhoneCode = "+30", Name = ResourceText.GREECE, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/23px-Flag_of_Greece.svg.png" },
                new CountryModel{Id = CountryEnum.GREENLAND, PhoneCode = "+299", Name = ResourceText.GREENLAND, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Greenland.svg/23px-Flag_of_Greenland.svg.png" },
                new CountryModel{Id = CountryEnum.GUADALUPE, PhoneCode = "+590", Name = ResourceText.GUADALUPE, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png" },
                new CountryModel{Id = CountryEnum.GUAM, PhoneCode = "+671", Name = ResourceText.GUAM, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Flag_of_Guam.svg/23px-Flag_of_Guam.svg.png" },
                new CountryModel{Id = CountryEnum.GUATEMALA, PhoneCode = "+502", Name = ResourceText.GUATEMALA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Flag_of_Guatemala.svg/23px-Flag_of_Guatemala.svg.png" },
                new CountryModel{Id = CountryEnum.GUYANA, PhoneCode = "+592", Name = ResourceText.GUYANA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_Guyana.svg/23px-Flag_of_Guyana.svg.png" },
                new CountryModel{Id = CountryEnum.FRENCH_GUIANA, PhoneCode = "+594", Name = ResourceText.FRENCH_GUIANA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_French_Guiana.svg/23px-Flag_of_French_Guiana.svg.png" },
                new CountryModel{Id = CountryEnum.GUINEA, PhoneCode = "+224", Name = ResourceText.GUINEA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_Guinea.svg/23px-Flag_of_Guinea.svg.png" },
                new CountryModel{Id = CountryEnum.GUINEA_BISSAU, PhoneCode = "+245", Name = ResourceText.GUINEA_BISSAU, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Guinea-Bissau.svg/23px-Flag_of_Guinea-Bissau.svg.png" },
                new CountryModel{Id = CountryEnum.EQUATORIAL_GUINEA, PhoneCode = "+240", Name = ResourceText.EQUATORIAL_GUINEA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Equatorial_Guinea.svg/23px-Flag_of_Equatorial_Guinea.svg.png" },
                new CountryModel{Id = CountryEnum.HAITI, PhoneCode = "+509", Name = ResourceText.HAITI, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Haiti.svg/23px-Flag_of_Haiti.svg.png" },
                new CountryModel{Id = CountryEnum.HONDURAS, PhoneCode = "+504", Name = ResourceText.HONDURAS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Honduras_%282008_Olympics%29.svg/23px-Flag_of_Honduras_%282008_Olympics%29.svg.png" },
                new CountryModel{Id = CountryEnum.HONG_KONG, PhoneCode = "+852", Name = ResourceText.HONG_KONG, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Hong_Kong.svg/23px-Flag_of_Hong_Kong.svg.png" },
                new CountryModel{Id = CountryEnum.HUNGARY, PhoneCode = "+36", Name = ResourceText.HUNGARY, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/23px-Flag_of_Hungary.svg.png" },
                new CountryModel{Id = CountryEnum.YEMEN, PhoneCode = "+967", Name = ResourceText.YEMEN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Yemen.svg/23px-Flag_of_Yemen.svg.png" },
                new CountryModel{Id = CountryEnum.CAYMAN_ISLANDS, PhoneCode = "+1", Name = ResourceText.CAYMAN_ISLANDS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_the_Cayman_Islands.svg/23px-Flag_of_the_Cayman_Islands.svg.png" },
                new CountryModel{Id = CountryEnum.CHRISTMAS_ISLAND, PhoneCode = "+672", Name = ResourceText.CHRISTMAS_ISLAND, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Flag_of_Christmas_Island.svg/23px-Flag_of_Christmas_Island.svg.png" },
                new CountryModel{Id = CountryEnum.COCOS_ISLANDS, PhoneCode = "+672", Name = ResourceText.COCOS_ISLANDS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Cocos_%28Keeling%29_Islands.svg/23px-Flag_of_the_Cocos_%28Keeling%29_Islands.svg.png" },
                new CountryModel{Id = CountryEnum.COOK_ISLANDS, PhoneCode = "+682", Name = ResourceText.COOK_ISLANDS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Flag_of_the_Cook_Islands.svg/23px-Flag_of_the_Cook_Islands.svg.png" },
                new CountryModel{Id = CountryEnum.FAROE_ISLANDS, PhoneCode = "+298", Name = ResourceText.FAROE_ISLANDS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Flag_of_the_Faroe_Islands.svg/21px-Flag_of_the_Faroe_Islands.svg.png" },
                new CountryModel{Id = CountryEnum.HEARD_ISLANDS_AND_MCDONALD_ISLANDS, PhoneCode = "+672", Name = ResourceText.HEARD_ISLANDS_AND_MCDONALD_ISLANDS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/23px-Flag_of_Australia.svg.png" },
                new CountryModel{Id = CountryEnum.MALDIVES, PhoneCode = "+960", Name = ResourceText.MALDIVES, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Maldives.svg/23px-Flag_of_Maldives.svg.png" },
                new CountryModel{Id = CountryEnum.FALKLAND_ISLANDS, PhoneCode = "+500", Name = ResourceText.FALKLAND_ISLANDS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_Falkland_Islands.svg/23px-Flag_of_the_Falkland_Islands.svg.png" },
                new CountryModel{Id = CountryEnum.NORTHERN_MARIANA_ISLANDS, PhoneCode = "+1", Name = ResourceText.NORTHERN_MARIANA_ISLANDS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Flag_of_the_Northern_Mariana_Islands.svg/23px-Flag_of_the_Northern_Mariana_Islands.svg.png" },
                new CountryModel{Id = CountryEnum.MARSHALL_ISLANDS, PhoneCode = "+692", Name = ResourceText.MARSHALL_ISLANDS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Flag_of_the_Marshall_Islands.svg/23px-Flag_of_the_Marshall_Islands.svg.png" },
                new CountryModel{Id = CountryEnum.NORFOLK_ISLAND, PhoneCode = "+672", Name = ResourceText.NORFOLK_ISLAND, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Norfolk_Island.svg/23px-Flag_of_Norfolk_Island.svg.png" },
                new CountryModel{Id = CountryEnum.SOLOMON_ISLANDS, PhoneCode = "+677", Name = ResourceText.SOLOMON_ISLANDS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Solomon_Islands.svg/23px-Flag_of_the_Solomon_Islands.svg.png" },
                new CountryModel{Id = CountryEnum.UNITED_STATES_VIRGIN_ISLANDS, PhoneCode = "+1", Name = ResourceText.UNITED_STATES_VIRGIN_ISLANDS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Flag_of_the_United_States_Virgin_Islands.svg/23px-Flag_of_the_United_States_Virgin_Islands.svg.png" },
                new CountryModel{Id = CountryEnum.BRITISH_VIRGIN_ISLANDS, PhoneCode = "+1", Name = ResourceText.BRITISH_VIRGIN_ISLANDS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_the_British_Virgin_Islands.svg/23px-Flag_of_the_British_Virgin_Islands.svg.png" },
                new CountryModel{Id = CountryEnum.INDIA, PhoneCode = "+91", Name = ResourceText.INDIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png" },
                new CountryModel{Id = CountryEnum.INDONESIA, PhoneCode = "+62", Name = ResourceText.INDONESIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/23px-Flag_of_Indonesia.svg.png" },
                new CountryModel{Id = CountryEnum.IRAN, PhoneCode = "+98", Name = ResourceText.IRAN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/23px-Flag_of_Iran.svg.png" },
                new CountryModel{Id = CountryEnum.IRAQ, PhoneCode = "+964", Name = ResourceText.IRAQ, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/23px-Flag_of_Iraq.svg.png" },
                new CountryModel{Id = CountryEnum.IRELAND, PhoneCode = "+353", Name = ResourceText.IRELAND, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/23px-Flag_of_Ireland.svg.png" },
                new CountryModel{Id = CountryEnum.ICELAND, PhoneCode = "+354", Name = ResourceText.ICELAND, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/21px-Flag_of_Iceland.svg.png" },
                new CountryModel{Id = CountryEnum.ISRAEL, PhoneCode = "+972", Name = ResourceText.ISRAEL, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/21px-Flag_of_Israel.svg.png" },
                new CountryModel{Id = CountryEnum.ITALY, PhoneCode = "+39", Name = ResourceText.ITALY, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/23px-Flag_of_Italy.svg.png" },
                new CountryModel{Id = CountryEnum.JAMAICA, PhoneCode = "+1", Name = ResourceText.JAMAICA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/23px-Flag_of_Jamaica.svg.png" },
                new CountryModel{Id = CountryEnum.JAPAN, PhoneCode = "+81", Name = ResourceText.JAPAN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/23px-Flag_of_Japan.svg.png" },
                new CountryModel{Id = CountryEnum.JORDAN, PhoneCode = "+962", Name = ResourceText.JORDAN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/23px-Flag_of_Jordan.svg.png" },
                new CountryModel{Id = CountryEnum.KIRIBATI, PhoneCode = "+686", Name = ResourceText.KIRIBATI, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kiribati.svg/23px-Flag_of_Kiribati.svg.png" },
                new CountryModel{Id = CountryEnum.KOSOVO, PhoneCode = "+383", Name = ResourceText.KOSOVO, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Flag_of_Kosovo.svg/21px-Flag_of_Kosovo.svg.png" },
                new CountryModel{Id = CountryEnum.KUWAIT, PhoneCode = "+965", Name = ResourceText.KUWAIT, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/23px-Flag_of_Kuwait.svg.png" },
                new CountryModel{Id = CountryEnum.LAOS, PhoneCode = "+856", Name = ResourceText.LAOS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Laos.svg/23px-Flag_of_Laos.svg.png" },
                new CountryModel{Id = CountryEnum.LESOTHO, PhoneCode = "+266", Name = ResourceText.LESOTHO, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/23px-Flag_of_Lesotho.svg.png" },
                new CountryModel{Id = CountryEnum.LATVIA, PhoneCode = "+371", Name = ResourceText.LATVIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/23px-Flag_of_Latvia.svg.png" },
                new CountryModel{Id = CountryEnum.LEBANON, PhoneCode = "+961", Name = ResourceText.LEBANON, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/23px-Flag_of_Lebanon.svg.png" },
                new CountryModel{Id = CountryEnum.LIBERIA, PhoneCode = "+231", Name = ResourceText.LIBERIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Flag_of_Liberia.svg/23px-Flag_of_Liberia.svg.png" },
                new CountryModel{Id = CountryEnum.LIBYA, PhoneCode = "+218", Name = ResourceText.LIBYA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/23px-Flag_of_Libya.svg.png" },
                new CountryModel{Id = CountryEnum.LIECHTENSTEIN, PhoneCode = "+423", Name = ResourceText.LIECHTENSTEIN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/23px-Flag_of_Liechtenstein.svg.png" },
                new CountryModel{Id = CountryEnum.LITHUANIA, PhoneCode = "+370", Name = ResourceText.LITHUANIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/23px-Flag_of_Lithuania.svg.png" },
                new CountryModel{Id = CountryEnum.LUXEMBOURG, PhoneCode = "+352", Name = ResourceText.LUXEMBOURG, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/23px-Flag_of_Luxembourg.svg.png" },
                new CountryModel{Id = CountryEnum.MACAU, PhoneCode = "+853", Name = ResourceText.MACAU, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Flag_of_Macau.svg/23px-Flag_of_Macau.svg.png" },
                new CountryModel{Id = CountryEnum.NORTH_MACEDONIA, PhoneCode = "+389", Name = ResourceText.NORTH_MACEDONIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_North_Macedonia.svg/23px-Flag_of_North_Macedonia.svg.png" },
                new CountryModel{Id = CountryEnum.MADAGASCAR, PhoneCode = "+261", Name = ResourceText.MADAGASCAR, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Madagascar.svg/23px-Flag_of_Madagascar.svg.png" },
                new CountryModel{Id = CountryEnum.MALAYSIA, PhoneCode = "+60", Name = ResourceText.MALAYSIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/23px-Flag_of_Malaysia.svg.png" },
                new CountryModel{Id = CountryEnum.MALAWI, PhoneCode = "+49", Name = ResourceText.MALAWI, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Flag_of_Malawi.svg/23px-Flag_of_Malawi.svg.png" },
                new CountryModel{Id = CountryEnum.MALI, PhoneCode = "+223", Name = ResourceText.MALI, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Mali.svg/23px-Flag_of_Mali.svg.png" },
                new CountryModel{Id = CountryEnum.MALTA, PhoneCode = "+356", Name = ResourceText.MALTA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/23px-Flag_of_Malta.svg.png" },
                new CountryModel{Id = CountryEnum.MOROCCO, PhoneCode = "+212", Name = ResourceText.MOROCCO, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/23px-Flag_of_Morocco.svg.png" },
                new CountryModel{Id = CountryEnum.MARTINICA, PhoneCode = "+49", Name = ResourceText.MARTINICA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png" },
                new CountryModel{Id = CountryEnum.MAURITIUS, PhoneCode = "+230", Name = ResourceText.MAURITIUS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/23px-Flag_of_Mauritius.svg.png" },
                new CountryModel{Id = CountryEnum.MAURITANIA, PhoneCode = "+222", Name = ResourceText.MAURITANIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Flag_of_Mauritania.svg/23px-Flag_of_Mauritania.svg.png" },
                new CountryModel{Id = CountryEnum.MAYOTTE, PhoneCode = "+269", Name = ResourceText.MAYOTTE, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png" },
                new CountryModel{Id = CountryEnum.MEXICO, PhoneCode = "+52", Name = ResourceText.MEXICO, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/23px-Flag_of_Mexico.svg.png" },
                new CountryModel{Id = CountryEnum.FEDERATED_STATES_OF_MICRONESIA, PhoneCode = "+691", Name = ResourceText.FEDERATED_STATES_OF_MICRONESIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg/23px-Flag_of_the_Federated_States_of_Micronesia.svg.png" },
                new CountryModel{Id = CountryEnum.MOZAMBIQUE, PhoneCode = "+258", Name = ResourceText.MOZAMBIQUE, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Mozambique.svg/23px-Flag_of_Mozambique.svg.png" },
                new CountryModel{Id = CountryEnum.MOLDOVA, PhoneCode = "+373", Name = ResourceText.MOLDOVA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/23px-Flag_of_Moldova.svg.png" },
                new CountryModel{Id = CountryEnum.MONACO, PhoneCode = "+377", Name = ResourceText.MONACO, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Monaco.svg/19px-Flag_of_Monaco.svg.png" },
                new CountryModel{Id = CountryEnum.MONGOLIA, PhoneCode = "+976", Name = ResourceText.MONGOLIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Mongolia.svg/23px-Flag_of_Mongolia.svg.png" },
                new CountryModel{Id = CountryEnum.MONTENEGRO, PhoneCode = "+382", Name = ResourceText.MONTENEGRO, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Montenegro.svg/23px-Flag_of_Montenegro.svg.png" },
                new CountryModel{Id = CountryEnum.MONTSERRAT, PhoneCode = "+1", Name = ResourceText.MONTSERRAT, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Montserrat.svg/23px-Flag_of_Montserrat.svg.png" },
                new CountryModel{Id = CountryEnum.MYANMAR, PhoneCode = "+95", Name = ResourceText.MYANMAR, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/23px-Flag_of_Myanmar.svg.png" },
                new CountryModel{Id = CountryEnum.NAMIBIA, PhoneCode = "+264", Name = ResourceText.NAMIBIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/23px-Flag_of_Namibia.svg.png" },
                new CountryModel{Id = CountryEnum.NAURU, PhoneCode = "+674", Name = ResourceText.NAURU, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Flag_of_Nauru.svg/23px-Flag_of_Nauru.svg.png" },
                new CountryModel{Id = CountryEnum.NEPAL, PhoneCode = "+977", Name = ResourceText.NEPAL, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/12px-Flag_of_Nepal.svg.png" },
                new CountryModel{Id = CountryEnum.NICARAGUA, PhoneCode = "+505", Name = ResourceText.NICARAGUA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Nicaragua.svg/23px-Flag_of_Nicaragua.svg.png" },
                new CountryModel{Id = CountryEnum.NIGER, PhoneCode = "+227", Name = ResourceText.NIGER, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Flag_of_Niger.svg/18px-Flag_of_Niger.svg.png" },
                new CountryModel{Id = CountryEnum.NIGERIA, PhoneCode = "+234", Name = ResourceText.NIGERIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/23px-Flag_of_Nigeria.svg.png" },
                new CountryModel{Id = CountryEnum.NIUE, PhoneCode = "+683", Name = ResourceText.NIUE, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Niue.svg/23px-Flag_of_Niue.svg.png" },
                new CountryModel{Id = CountryEnum.NORWAY, PhoneCode = "+47", Name = ResourceText.NORWAY, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/21px-Flag_of_Norway.svg.png" },
                new CountryModel{Id = CountryEnum.NEW_CALEDONIA, PhoneCode = "+687", Name = ResourceText.NEW_CALEDONIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flags_of_New_Caledonia.svg/40px-Flags_of_New_Caledonia.svg.png" },
                new CountryModel{Id = CountryEnum.NEW_ZEALAND, PhoneCode = "+64", Name = ResourceText.NEW_ZEALAND, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/23px-Flag_of_New_Zealand.svg.png" },
                new CountryModel{Id = CountryEnum.OMAN, PhoneCode = "+968", Name = ResourceText.OMAN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/23px-Flag_of_Oman.svg.png" },
                new CountryModel{Id = CountryEnum.NETHERLANDS, PhoneCode = "+31", Name = ResourceText.NETHERLANDS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/23px-Flag_of_the_Netherlands.svg.png" },
                new CountryModel{Id = CountryEnum.PALAU, PhoneCode = "+680", Name = ResourceText.PALAU, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Palau.svg/23px-Flag_of_Palau.svg.png" },
                new CountryModel{Id = CountryEnum.PALESTINE, PhoneCode = "+970", Name = ResourceText.PALESTINE, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/23px-Flag_of_Palestine.svg.png" },
                new CountryModel{Id = CountryEnum.PANAMA, PhoneCode = "+507", Name = ResourceText.PANAMA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/23px-Flag_of_Panama.svg.png" },
                new CountryModel{Id = CountryEnum.PAPUA_NEW_GUINEA, PhoneCode = "+675", Name = ResourceText.PAPUA_NEW_GUINEA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/20px-Flag_of_Papua_New_Guinea.svg.png" },
                new CountryModel{Id = CountryEnum.PAKISTAN, PhoneCode = "+92", Name = ResourceText.PAKISTAN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/23px-Flag_of_Pakistan.svg.png" },
                new CountryModel{Id = CountryEnum.PARAGUAY, PhoneCode = "+595", Name = ResourceText.PARAGUAY, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/23px-Flag_of_Paraguay.svg.png" },
                new CountryModel{Id = CountryEnum.PERU, PhoneCode = "+51", Name = ResourceText.PERU, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/23px-Flag_of_Peru.svg.png" },
                new CountryModel{Id = CountryEnum.FRENCH_POLYNESIA, PhoneCode = "+689", Name = ResourceText.FRENCH_POLYNESIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Flag_of_French_Polynesia.svg/23px-Flag_of_French_Polynesia.svg.png" },
                new CountryModel{Id = CountryEnum.POLAND, PhoneCode = "+48", Name = ResourceText.POLAND, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/23px-Flag_of_Poland.svg.png" },
                new CountryModel{Id = CountryEnum.PUERTO_RICO, PhoneCode = "+1", Name = ResourceText.PUERTO_RICO, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/23px-Flag_of_Puerto_Rico.svg.png" },
                new CountryModel{Id = CountryEnum.PORTUGAL, PhoneCode = "+351", Name = ResourceText.PORTUGAL, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/23px-Flag_of_Portugal.svg.png" },
                new CountryModel{Id = CountryEnum.QATAR, PhoneCode = "+974", Name = ResourceText.QATAR, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/23px-Flag_of_Qatar.svg.png" },
                new CountryModel{Id = CountryEnum.KENYA, PhoneCode = "+254", Name = ResourceText.KENYA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/23px-Flag_of_Kenya.svg.png" },
                new CountryModel{Id = CountryEnum.KYRGYZSTAN, PhoneCode = "+996", Name = ResourceText.KYRGYZSTAN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/23px-Flag_of_Kyrgyzstan.svg.png" },
                new CountryModel{Id = CountryEnum.UNITED_KINGDOM, PhoneCode = "+44", Name = ResourceText.UNITED_KINGDOM, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Flag_of_the_United_Kingdom.svg/23px-Flag_of_the_United_Kingdom.svg.png" },
                new CountryModel{Id = CountryEnum.CENTRAL_AFRICAN_REPUBLIC, PhoneCode = "+236", Name = ResourceText.CENTRAL_AFRICAN_REPUBLIC, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Central_African_Republic.svg/23px-Flag_of_the_Central_African_Republic.svg.png" },
                new CountryModel{Id = CountryEnum.DOMINICAN_REPUBLIC, PhoneCode = "+1", Name = ResourceText.DOMINICAN_REPUBLIC, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/23px-Flag_of_the_Dominican_Republic.svg.png" },
                new CountryModel{Id = CountryEnum.CZECH_REPUBLIC, PhoneCode = "+420", Name = ResourceText.CZECH_REPUBLIC, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/23px-Flag_of_the_Czech_Republic.svg.png" },
                new CountryModel{Id = CountryEnum.REUNION_ISLAND, PhoneCode = "+262", Name = ResourceText.REUNION_ISLAND, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png" },
                new CountryModel{Id = CountryEnum.ROMANIA, PhoneCode = "+40", Name = ResourceText.ROMANIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/23px-Flag_of_Romania.svg.png" },
                new CountryModel{Id = CountryEnum.RWANDA, PhoneCode = "+250", Name = ResourceText.RWANDA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/23px-Flag_of_Rwanda.svg.png" },
                new CountryModel{Id = CountryEnum.RUSSIA, PhoneCode = "+7", Name = ResourceText.RUSSIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/23px-Flag_of_Russia.svg.png" },
                new CountryModel{Id = CountryEnum.SAHRAWI_ARAB_DEMOCRATIC_REPUBLIC, PhoneCode = "+212", Name = ResourceText.SAHRAWI_ARAB_DEMOCRATIC_REPUBLIC, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg/23px-Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg.png" },
                new CountryModel{Id = CountryEnum.SAMOA, PhoneCode = "+685", Name = ResourceText.SAMOA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Samoa.svg/23px-Flag_of_Samoa.svg.png" },
                new CountryModel{Id = CountryEnum.AMERICAN_SAMOA, PhoneCode = "+1", Name = ResourceText.AMERICAN_SAMOA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Flag_of_American_Samoa.svg/23px-Flag_of_American_Samoa.svg.png" },
                new CountryModel{Id = CountryEnum.SAINT_HELENA, PhoneCode = "+290", Name = ResourceText.SAINT_HELENA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Saint_Helena.svg/23px-Flag_of_Saint_Helena.svg.png" },
                new CountryModel{Id = CountryEnum.SAINT_LUCIA, PhoneCode = "+1", Name = ResourceText.SAINT_LUCIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Saint_Lucia.svg/23px-Flag_of_Saint_Lucia.svg.png" },
                new CountryModel{Id = CountryEnum.SAINT_KITTS_AND_NEVIS, PhoneCode = "+1", Name = ResourceText.SAINT_KITTS_AND_NEVIS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg/23px-Flag_of_Saint_Kitts_and_Nevis.svg.png" },
                new CountryModel{Id = CountryEnum.SAN_MARINO, PhoneCode = "+378", Name = ResourceText.SAN_MARINO, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_San_Marino.svg/20px-Flag_of_San_Marino.svg.png" },
                new CountryModel{Id = CountryEnum.SAINT_PIERRE_AND_MIQUELON, PhoneCode = "+508", Name = ResourceText.SAINT_PIERRE_AND_MIQUELON, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png" },
                new CountryModel{Id = CountryEnum.SAO_TOME_AND_PRINCIPE, PhoneCode = "+355", Name = ResourceText.SAO_TOME_AND_PRINCIPE, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Sao_Tome_and_Principe.svg/23px-Flag_of_Sao_Tome_and_Principe.svg.png" },
                new CountryModel{Id = CountryEnum.SAINT_VINCENT_AND_THE_GRENADINES, PhoneCode = "+1", Name = ResourceText.SAINT_VINCENT_AND_THE_GRENADINES, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg/23px-Flag_of_Saint_Vincent_and_the_Grenadines.svg.png" },
                new CountryModel{Id = CountryEnum.SEYCHELLES, PhoneCode = "+248", Name = ResourceText.SEYCHELLES, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Seychelles.svg/23px-Flag_of_Seychelles.svg.png" },
                new CountryModel{Id = CountryEnum.SENEGAL, PhoneCode = "+221", Name = ResourceText.SENEGAL, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/23px-Flag_of_Senegal.svg.png" },
                new CountryModel{Id = CountryEnum.SIERRA_LEONE, PhoneCode = "+232", Name = ResourceText.SIERRA_LEONE, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Sierra_Leone.svg/23px-Flag_of_Sierra_Leone.svg.png" },
                new CountryModel{Id = CountryEnum.SERBIA, PhoneCode = "+381", Name = ResourceText.SERBIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/23px-Flag_of_Serbia.svg.png" },
                new CountryModel{Id = CountryEnum.SINGAPORE, PhoneCode = "+65", Name = ResourceText.SINGAPORE, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/23px-Flag_of_Singapore.svg.png" },
                new CountryModel{Id = CountryEnum.SYRIA, PhoneCode = "+963", Name = ResourceText.SYRIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Flag_of_Syria.svg/23px-Flag_of_Syria.svg.png" },
                new CountryModel{Id = CountryEnum.SOMALIA, PhoneCode = "+252", Name = ResourceText.SOMALIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Somalia.svg/23px-Flag_of_Somalia.svg.png" },
                new CountryModel{Id = CountryEnum.SRI_LANKA, PhoneCode = "+94", Name = ResourceText.SRI_LANKA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/23px-Flag_of_Sri_Lanka.svg.png" },
                new CountryModel{Id = CountryEnum.ESWATINI, PhoneCode = "+268", Name = ResourceText.ESWATINI, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Eswatini.svg/23px-Flag_of_Eswatini.svg.png" },
                new CountryModel{Id = CountryEnum.SUDAN, PhoneCode = "+249", Name = ResourceText.SUDAN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/23px-Flag_of_Sudan.svg.png" },
                new CountryModel{Id = CountryEnum.SOUTH_SUDAN, PhoneCode = "+211", Name = ResourceText.SOUTH_SUDAN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Flag_of_South_Sudan.svg/23px-Flag_of_South_Sudan.svg.png" },
                new CountryModel{Id = CountryEnum.SWEDEN, PhoneCode = "+46", Name = ResourceText.SWEDEN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Sweden.svg/23px-Flag_of_Sweden.svg.png" },
                new CountryModel{Id = CountryEnum.SWITZERLAND, PhoneCode = "+41", Name = ResourceText.SWITZERLAND, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/16px-Flag_of_Switzerland.svg.png" },
                new CountryModel{Id = CountryEnum.SURINAME, PhoneCode = "+597", Name = ResourceText.SURINAME, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Flag_of_Suriname.svg/23px-Flag_of_Suriname.svg.png" },
                new CountryModel{Id = CountryEnum.TAJIKISTAN, PhoneCode = "+992", Name = ResourceText.TAJIKISTAN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/23px-Flag_of_Tajikistan.svg.png" },
                new CountryModel{Id = CountryEnum.THAILAND, PhoneCode = "+66", Name = ResourceText.THAILAND, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/23px-Flag_of_Thailand.svg.png" },
                new CountryModel{Id = CountryEnum.REPUBLIC_OF_CHINA, PhoneCode = "+886", Name = ResourceText.REPUBLIC_OF_CHINA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/23px-Flag_of_the_Republic_of_China.svg.png" },
                new CountryModel{Id = CountryEnum.TANZANIA, PhoneCode = "+255", Name = ResourceText.TANZANIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/23px-Flag_of_Tanzania.svg.png" },
                new CountryModel{Id = CountryEnum.BRITISH_INDIAN_OCEAN_TERRITORY, PhoneCode = "+246", Name = ResourceText.BRITISH_INDIAN_OCEAN_TERRITORY, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_the_Commissioner_of_the_British_Indian_Ocean_Territory.svg/23px-Flag_of_the_Commissioner_of_the_British_Indian_Ocean_Territory.svg.png" },
                new CountryModel{Id = CountryEnum.EAST_TIMOR, PhoneCode = "+49", Name = ResourceText.EAST_TIMOR, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_East_Timor.svg/23px-Flag_of_East_Timor.svg.png" },
                new CountryModel{Id = CountryEnum.TOGO, PhoneCode = "+228", Name = ResourceText.TOGO, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Flag_of_Togo.svg/23px-Flag_of_Togo.svg.png" },
                new CountryModel{Id = CountryEnum.TOKELAU, PhoneCode = "+690", Name = ResourceText.TOKELAU, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Flag_of_Tokelau.svg/23px-Flag_of_Tokelau.svg.png" },
                new CountryModel{Id = CountryEnum.TONGA, PhoneCode = "+676", Name = ResourceText.TONGA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Tonga.svg/23px-Flag_of_Tonga.svg.png" },
                new CountryModel{Id = CountryEnum.TRINIDAD_AND_TOBAGO, PhoneCode = "+1", Name = ResourceText.TRINIDAD_AND_TOBAGO, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Trinidad_and_Tobago.svg/23px-Flag_of_Trinidad_and_Tobago.svg.png" },
                new CountryModel{Id = CountryEnum.TUNISIA, PhoneCode = "+216", Name = ResourceText.TUNISIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/23px-Flag_of_Tunisia.svg.png" },
                new CountryModel{Id = CountryEnum.TURKS_AND_CAICOS_ISLANDS, PhoneCode = "+1", Name = ResourceText.TURKS_AND_CAICOS_ISLANDS, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg/23px-Flag_of_the_Turks_and_Caicos_Islands.svg.png" },
                new CountryModel{Id = CountryEnum.TURKMENISTAN, PhoneCode = "+993", Name = ResourceText.TURKMENISTAN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Turkmenistan.svg/23px-Flag_of_Turkmenistan.svg.png" },
                new CountryModel{Id = CountryEnum.TURKEY, PhoneCode = "+90", Name = ResourceText.TURKEY, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/23px-Flag_of_Turkey.svg.png" },
                new CountryModel{Id = CountryEnum.TUVALU, PhoneCode = "+688", Name = ResourceText.TUVALU, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tuvalu.svg/23px-Flag_of_Tuvalu.svg.png" },
                new CountryModel{Id = CountryEnum.UKRAINE, PhoneCode = "+380", Name = ResourceText.UKRAINE, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/23px-Flag_of_Ukraine.svg.png" },
                new CountryModel{Id = CountryEnum.UGANDA, PhoneCode = "+256", Name = ResourceText.UGANDA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/23px-Flag_of_Uganda.svg.png" },
                new CountryModel{Id = CountryEnum.URUGUAY, PhoneCode = "+598", Name = ResourceText.URUGUAY, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/23px-Flag_of_Uruguay.svg.png" },
                new CountryModel{Id = CountryEnum.UZBEKISTAN, PhoneCode = "+998", Name = ResourceText.UZBEKISTAN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/23px-Flag_of_Uzbekistan.svg.png" },
                new CountryModel{Id = CountryEnum.VANUATU, PhoneCode = "+678", Name = ResourceText.VANUATU, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Vanuatu.svg/23px-Flag_of_Vanuatu.svg.png" },
                new CountryModel{Id = CountryEnum.VATICAN, PhoneCode = "+379", Name = ResourceText.VATICAN, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_the_Vatican_City.svg/15px-Flag_of_the_Vatican_City.svg.png" },
                new CountryModel{Id = CountryEnum.VENEZUELA, PhoneCode = "+58", Name = ResourceText.VENEZUELA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Venezuela.svg/23px-Flag_of_Venezuela.svg.png" },
                new CountryModel{Id = CountryEnum.VIETNAM, PhoneCode = "+84", Name = ResourceText.VIETNAM, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/23px-Flag_of_Vietnam.svg.png" },
                new CountryModel{Id = CountryEnum.WALLIS_AND_FUTUNA, PhoneCode = "+681", Name = ResourceText.WALLIS_AND_FUTUNA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png" },
                new CountryModel{Id = CountryEnum.ZAMBIA, PhoneCode = "+260", Name = ResourceText.ZAMBIA, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/23px-Flag_of_Zambia.svg.png" },
                new CountryModel{Id = CountryEnum.ZIMBABWE, PhoneCode = "+263", Name = ResourceText.ZIMBABWE, Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/23px-Flag_of_Zimbabwe.svg.png" }
            }.OrderBy(c => c.Name).ToList();
        }
    }
    public enum CountryEnum
    {
        AFGHANISTAN = 1,
        SOUTH_AFRICA = 2,
        ALBANIA = 3,
        GERMANY = 4,
        ANDORRA = 5,
        ANGOLA = 6,
        ANGUILLA = 7,
        ANTIGUA_AND_BARBUDA = 8,
        NETHERLANDS_ANTILLES = 9,
        SAUDI_ARABIA = 10,
        ALGERIA = 11,
        ARGENTINA = 12,
        ARMENIA = 13,
        ARUBA = 14,
        ASCENSION = 15,
        AUSTRALIA = 16,
        AUSTRIA = 17,
        AZERBAIJAN = 18,
        BAHAMAS = 19,
        BANGLADESH = 20,
        BARBADOS = 21,
        BAHRAIN = 22,
        BELGIUM = 23,
        BELIZE = 24,
        BENIN = 25,
        BERMUDA = 26,
        BELARUS = 27,
        BOLIVIA = 28,
        BOSNIA_AND_HERZEGOVINA = 29,
        BOTSWANA = 30,
        BRAZIL = 31,
        BRUNEI = 32,
        BULGARIA = 33,
        BURKINA_FASO = 34,
        BURUNDI = 35,
        BHUTAN = 36,
        CAPE_VERDE = 37,
        CAMEROON = 38,
        CAMBODIA = 39,
        CANADA = 40,
        KAZAKHSTAN = 41,
        CHAD = 42,
        CHILE = 43,
        PEOPLE_REPUBLIC_OF_CHINA = 44,
        CYPRUS = 45,
        COLOMBIA = 46,
        COMOROS = 47,
        REPUBLIC_OF_THE_CONGO = 48,
        DEMOCRATIC_REPUBLIC_OF_THE_CONGO = 49,
        NORTH_KOREA = 50,
        SOUTH_KOREA = 51,
        IVORY_COAST = 52,
        COSTA_RICA = 53,
        CROATIA = 54,
        CUBA = 55,
        DENMARK = 56,
        DJIBOUTI = 57,
        DOMINICA = 58,
        EGYPT = 59,
        EL_SALVADOR = 60,
        UNITED_ARAB_EMIRATES = 61,
        ECUADOR = 62,
        ERITREA = 63,
        SLOVAKIA = 64,
        SLOVENIA = 65,
        SPAIN = 66,
        UNITED_STATES = 67,
        ESTONIA = 68,
        ETHIOPIA = 69,
        FIJI = 70,
        PHILIPPINES = 71,
        FINLAND = 72,
        FRANCE = 73,
        GABON = 74,
        GAMBIA = 75,
        GHANA = 76,
        GEORGIA = 77,
        GIBRALTAR = 78,
        GRENADA = 79,
        GREECE = 80,
        GREENLAND = 81,
        GUADALUPE = 82,
        GUAM = 83,
        GUATEMALA = 84,
        GUYANA = 85,
        FRENCH_GUIANA = 86,
        GUINEA = 87,
        GUINEA_BISSAU = 88,
        EQUATORIAL_GUINEA = 89,
        HAITI = 90,
        HONDURAS = 91,
        HONG_KONG = 92,
        HUNGARY = 93,
        YEMEN = 94,
        CAYMAN_ISLANDS = 95,
        CHRISTMAS_ISLAND = 96,
        COCOS_ISLANDS = 97,
        COOK_ISLANDS = 98,
        FAROE_ISLANDS = 99,
        HEARD_ISLANDS_AND_MCDONALD_ISLANDS = 100,
        MALDIVES = 101,
        FALKLAND_ISLANDS = 102,
        NORTHERN_MARIANA_ISLANDS = 103,
        MARSHALL_ISLANDS = 104,
        NORFOLK_ISLAND = 105,
        SOLOMON_ISLANDS = 106,
        UNITED_STATES_VIRGIN_ISLANDS = 107,
        BRITISH_VIRGIN_ISLANDS = 108,
        INDIA = 109,
        INDONESIA = 110,
        IRAN = 111,
        IRAQ = 112,
        IRELAND = 113,
        ICELAND = 114,
        ISRAEL = 115,
        ITALY = 116,
        JAMAICA = 117,
        JAPAN = 118,
        JORDAN = 119,
        KIRIBATI = 120,
        KOSOVO = 121,
        KUWAIT = 122,
        LAOS = 123,
        LESOTHO = 124,
        LATVIA = 125,
        LEBANON = 126,
        LIBERIA = 127,
        LIBYA = 128,
        LIECHTENSTEIN = 129,
        LITHUANIA = 130,
        LUXEMBOURG = 131,
        MACAU = 132,
        NORTH_MACEDONIA = 133,
        MADAGASCAR = 134,
        MALAYSIA = 135,
        MALAWI = 136,
        MALI = 137,
        MALTA = 138,
        MOROCCO = 139,
        MARTINICA = 140,
        MAURITIUS = 141,
        MAURITANIA = 142,
        MAYOTTE = 143,
        MEXICO = 144,
        FEDERATED_STATES_OF_MICRONESIA = 145,
        MOZAMBIQUE = 146,
        MOLDOVA = 147,
        MONACO = 148,
        MONGOLIA = 149,
        MONTENEGRO = 150,
        MONTSERRAT = 151,
        MYANMAR = 152,
        NAMIBIA = 153,
        NAURU = 154,
        NEPAL = 155,
        NICARAGUA = 156,
        NIGER = 157,
        NIGERIA = 158,
        NIUE = 159,
        NORWAY = 160,
        NEW_CALEDONIA = 161,
        NEW_ZEALAND = 162,
        OMAN = 163,
        NETHERLANDS = 164,
        PALAU = 165,
        PALESTINE = 166,
        PANAMA = 167,
        PAPUA_NEW_GUINEA = 168,
        PAKISTAN = 169,
        PARAGUAY = 170,
        PERU = 171,
        FRENCH_POLYNESIA = 172,
        POLAND = 173,
        PUERTO_RICO = 174,
        PORTUGAL = 175,
        QATAR = 176,
        KENYA = 177,
        KYRGYZSTAN = 178,
        UNITED_KINGDOM = 179,
        CENTRAL_AFRICAN_REPUBLIC = 180,
        DOMINICAN_REPUBLIC = 181,
        CZECH_REPUBLIC = 182,
        REUNION_ISLAND = 183,
        ROMANIA = 184,
        RWANDA = 185,
        RUSSIA = 186,
        SAHRAWI_ARAB_DEMOCRATIC_REPUBLIC = 187,
        SAMOA = 188,
        AMERICAN_SAMOA = 189,
        SAINT_HELENA = 190,
        SAINT_LUCIA = 191,
        SAINT_KITTS_AND_NEVIS = 192,
        SAN_MARINO = 193,
        SAINT_PIERRE_AND_MIQUELON = 194,
        SAO_TOME_AND_PRINCIPE = 195,
        SAINT_VINCENT_AND_THE_GRENADINES = 196,
        SEYCHELLES = 197,
        SENEGAL = 198,
        SIERRA_LEONE = 199,
        SERBIA = 200,
        SINGAPORE = 201,
        SYRIA = 202,
        SOMALIA = 203,
        SRI_LANKA = 204,
        ESWATINI = 205,
        SUDAN = 206,
        SOUTH_SUDAN = 207,
        SWEDEN = 208,
        SWITZERLAND = 209,
        SURINAME = 210,
        TAJIKISTAN = 211,
        THAILAND = 212,
        REPUBLIC_OF_CHINA = 213,
        TANZANIA = 214,
        BRITISH_INDIAN_OCEAN_TERRITORY = 215,
        EAST_TIMOR = 216,
        TOGO = 217,
        TOKELAU = 218,
        TONGA = 219,
        TRINIDAD_AND_TOBAGO = 220,
        TUNISIA = 221,
        TURKS_AND_CAICOS_ISLANDS = 222,
        TURKMENISTAN = 223,
        TURKEY = 224,
        TUVALU = 225,
        UKRAINE = 226,
        UGANDA = 227,
        URUGUAY = 228,
        UZBEKISTAN = 229,
        VANUATU = 230,
        VATICAN = 231,
        VENEZUELA = 232,
        VIETNAM = 233,
        WALLIS_AND_FUTUNA = 234,
        ZAMBIA = 235,
        ZIMBABWE = 236
    }
    public class CountryModel
    {
        public CountryEnum Id { get; set; }
        public string Name { get; set; }
        public string PhoneCode { get; set; }
        public string Flag { get; set; }
    }
}
