name: Build Project

on: [push, pull_request]

jobs:
  build:
    env:
      NETCORE_VERSION: '3.1.x'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      SolutionPath: 'IntelligentHabitacion.sln'
    
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      
    - name: Clean Solution
      run: msbuild.exe ${{ env.SolutionPath }} /t:Clean /p:configuration=${{ env.buildConfiguration }}
      
    - name: Restore Packages
      run: nuget restore ${{ env.SolutionPath }}
      
    - name: Build Solution
      run: msbuild.exe ${{ env.SolutionPath }} /restore /t:Build /p:ContinuousIntegrationBuild=true /p:Deterministic=false /p:Configuration=${{ env.buildConfiguration }} /p:platform=${{ env.buildPlatform }}
