name: .NET Build on Push and Pull_Request

on: [push, pull_request]

jobs:
  build:
    env:
      NETCORE_VERSION: '3.1.x'
      buildConfiguration: 'Release'
      SolutionPath: 'IntelligentHabitacion.sln'
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '16.8.0'
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ${{ env.SolutionPath }} -c ${{ env.buildConfiguration }}
    - name: Run Test
      run: dotnet test --no-build --verbosity normal
