name: .NET Build on Push and Pull_Request

on: [push, pull_request]

jobs:
  build:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      NETCORE_VERSION: '3.1.x'
      buildConfiguration: 'Release'
      SolutionPath: 'IntelligentHabitacion.sln'
    
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Clean Solution
      run: msbuild ${{ env.SolutionPath }} /t:Clean
